- api/go.sum
- api/turing/api/request/request_test.go
- api/turing/models/traffic_rules.go
- api/turing/models/traffic_rules_test.go
- api/turing/validation/validator.go
- api/turing/validation/validator_test.go
- engines/experiment/common/web_utils.go
- engines/experiment/common/web_utils_test.go
- engines/router/Makefile
- engines/router/missionctl/fiberapi/traffic_splitting_strategy.go
- engines/router/missionctl/fiberapi/traffic_splitting_strategy_test.go
- engines/router/missionctl/log/resultlog/resultlog.go
- engines/router/missionctl/log/resultlog/resultlog_test.go
- engines/router/traffic_rule_condition.go
- engines/router/traffic_rule_condition_test.go
PR 67:
- Omit empty values when logging request data
PR 68:
- Allow extraction of non-string properties from JSON payload
- Move TrafficRuleCondition from common to router package
> Backport internal pull request 67 and 68

- engines/router/missionctl/mission_control_test.go
Test HTTP server in mission control unit test is currently started asynchronously in a separate goroutine
https://github.com/gojek/turing/blob/27cb7c65a0d7ef00066749ad64ae7bb244425b73/engines/router/missionctl/mission_control_test.go#L368-L377
There can be cases where this HTTP server is not ready yet but the tests start sending test requests resulting in unexpected test failures such as https://github.com/gojek/turing/pull/9/checks?check_run_id=1320100978
This pull request modifies the helper function such that the HTTP server starts in a blocking manner, ensuring that when test requests are sent, the test server is always ready.
> Also added some assertion to check that the HTTP response is not Nil before retrieving the body to make the test error message clearer rather than having …
> Refactor test http server in mission control unit test so the test is more deterministic

- scripts/vertagen/vertagen.sh
This PR replicates the changes from internal MR 106.
The `vertagen` script was previously parsing the tags listed in the commit summary of the `git log` command. When more than one tag exists on the same commit, the `git log` command lists the tags in _descending alphabetical ordering_. This works for most cases (eg: if `v0.0.5-alpha1`, `v0.0.5-beta1` and `v0.0.5-rc1` exist on the same commit, the default ordering will list `v0.0.5-rc1` first, which is picked by the vertagen script). However, this behaviour is incorrect when pre-release tags are mixed with release tags.
Eg: `commit b7d40bb94aa0e0ebcd737c74e92871556e31e81f (tag: v0.0.5-rc1, tag: v0.0.5, origin/master)` lists the pre-release tag first, following the default ordering.
It is common to promote a pre-release build to a release …
> Update version gen script for correct release build ordering

- ui/.env.development
- ui/package-lock.json
- ui/package.json
- ui/src/PrivateLayout.js
- ui/src/PrivateLayout.scss
- ui/src/config.js
**What this PR does / why we need it:**
To standardize the navigation bar across MLP products, I update Turing's NavBar by using the latest @gojek/mlp-ui and updating the source code.
> UI: Update NavBar

- ui/README.md
- ui/src/PrivateLayout.scss
- ui/src/assets/style.scss
- ui/src/components/accordion_form/AccordionForm.scss
- ui/src/config.js
- ui/src/router/components/form/components/ResourcesPanel.js
As per title, currently it's hardcoded to `10`, but 10 could be not enough for some of the use cases, so we would like to make it more flexible and configured at the build time
> Make maxAllowedReplica config value configurable from env vars

- .github/workflows/e2e.yaml
- api/openapi.yaml
- api/openapi/jobs.yaml
- api/turing/api/ensembling_job_api.go
- api/turing/api/ensembling_job_api_it_test.go
- api/turing/api/ensembling_job_api_test.go
- api/turing/middleware/openapi_validation.go
- api/turing/service/ensembling_job_service.go
- api/turing/service/ensembling_job_service_test.go
This PR introduces the get and list endpoints for ensembling jobs.
> List/Get Ensembling job endpoints

- .github/workflows/engines-batch-ensembler.yaml
- test/e2e/kind.config.yaml
- test/e2e/setup-infra.sh
Currently, Github actions is not publishing to master. This will allow ensemblers to build on master.
> Build ensembler on master.

- ui/package-lock.json
- ui/package.json
- ui/src/App.js
- ui/src/components/status_health/DeploymentStatusHealth.js
- ui/src/config.js
- ui/src/job/list/ListEnsemblingJobsTable.js
- ui/src/job/list/ListEnsemblingJobsView.js
- ui/src/providers/ensemblers/context.js
- ui/src/router/components/status_health/DeploymentStatusHealth.js
- ui/src/router/list/ListRoutersTable.js
- ui/src/router/list/ListRoutersView.js
- ui/src/router/versions/details/version_details_header/VersionDetailsPageHeader.js
- ui/src/router/versions/list/ListRouterVersionsTable.js
- ui/src/services/enum_value/EnumValue.js
- ui/src/services/job_status/JobStatus.js
- ui/src/services/status/Status.js
This PR adds a simple view to list ensembling jobs within a project. It is also supplemented with https://github.com/gojek/mlp/pull/30, so users can easily navigate between `Routers` and `Jobs` sections.
> UI: List ensembling jobs

- README.md
Missed the readme file update in this PR: https://github.com/gojek/turing/pull/73
> Missed update readme for config file.

- ui/src/components/form/validation/multi_section_provider.js
Recently, the Router Form has begun to display performance degradation, especially when attempting to type into the text fields when the form has already been touched (which in turn causes the validation to be run repeatedly, with every key stroke). A similar behavior is seen even with a very simple `yup` validation schema for all steps. Additionally, this slowness is also noticeable in older versions of the code, albeit less pronounced.
Introducing a debouncing delay of `500ms` to the form validation so that it will only be run at most once every 500ms.
> Add debouncing to form validation

- engines/experiment/runner/types.go
These const key can be removed together with the previous [PR](https://github.com/gojek/turing/pull/141).
> Remove unused label

- engines/experiment/plugin/inproc/manager/manager_test.go
- engines/experiment/plugin/inproc/runner/runner_test.go
- engines/experiment/plugin/rpc/factory.go
- engines/experiment/plugin/rpc/factory_test.go
- engines/experiment/plugin/rpc/manager/rpc.go
- engines/experiment/plugin/rpc/manager/rpc_test.go
- engines/experiment/plugin/rpc/rpc.go
- engines/experiment/plugin/rpc/runner/rpc.go
- engines/experiment/plugin/rpc/runner/rpc_test.go
- engines/experiment/plugin/rpc/runner/runner.go
I've accidentally merged https://github.com/gojek/turing/pull/143 before the CI pipeline succeeded, which left some of the linter errors not addressed in the previous PR. This is fixing that unfortunate mistake.
> Fix Linter

- api/go.sum
- api/turing/cluster/knative_service.go
- api/turing/cluster/knative_service_test.go
The annotation `queue.sidecar.serving.knative.dev/resourcePercentage` will not be set on the Knative service if the configured value is <= 0.
> Do not set knative resource percentage annotation if value <= 0

- .github/workflows/cluster-init.yaml
Bugfix the publish workflow - https://github.com/gojek/turing/runs/4788151149?check_suite_focus=true
> patch publish docker image in cluster-init workflow

- api/turing/service/router_deployment_service.go
The existing router deployment (`DeployRouterVersion`) and undeployment  (`UndeployRouterVersion`) functions do not build and teardown components in the same order. While in most cases, this should not pose any issues, in instances where `UndeployRouterVersion` is used as a subroutine to teardown a router version that has been partially deployed (but has subsequently encountered an error) using `DeployRouterVersion`, a potential problem can occur whereby artifacts created during the deployment fail to get deleted.
One such occurrence is with the implementation of `deployOrRollbackRouter`, which calls `deployRouterVersion` and subsequently `DeployRouterVersion` to deploy a router version, but triggers `UndeployRouterVersion` if it encounters an error during deployment. 
Of particular …
> Reorder undeployment service which skips secret deletion

- infra/charts/turing/Chart.yaml
- infra/charts/turing/README.md
- infra/charts/turing/values.yaml
This PR:
* Bumps Turing chart version (to 0.2.7)
* Updates the version of the Turing Server/Router images
* Updates chart's README.md
> [Chart] Turing chart version 0.2.7

- infra/charts/turing/Chart.yaml
- infra/charts/turing/README.md
- infra/charts/turing/values.yaml
Updating the chart version and default app/router version, for the upcoming prod release.
> Bump up chart values and version for release

- api/go.mod
- api/go.sum
- api/turing/validation/validator.go
- api/turing/validation/validator_test.go
**What this PR does / why we need it**:
With the recent improvements to Traffic Rules, this PR adds an additional layer of validation for users, to validate that Traffic Rule conditions are not overlapping. Any violations will be returned in an error response that can be rectified by the user easily.
> Add validation for overlapping rules

- ui/package.json
- ui/src/router/components/configuration/components/router_config_section/RoutesConfigTable.js
- ui/src/router/components/configuration/components/router_config_section/RulesConfigTable.js
- ui/yarn.lock
**What this PR does / why we need it**:
This PR consists of UI bug fixes:
- Bug fixes from mlp-ui dependency: https://github.com/gojek/mlp/pull/59
- Some bugs was introduced in a previous [PR](https://github.com/caraml-dev/turing/pull/239)
- where the RulesConfigTable considered the presence of Default Traffic Rule for Routers with no Traffic Rules.
- where the RoutesConfigTable showed an expansion button even with no Traffic Rules
> UI bug fix and mlp-ui dependency upgrade

- ui/src/components/pod_logs_viewer/PodLogsViewer.js
With the recent upgrade of Eui, the search bar's `field_value_selection` with single-select no longer works as expected. Logged it here: https://github.com/elastic/eui/issues/6271
However, `multiSelect` set to and/or works and since we want it to behave as a single-select, we can simply take the latest value from the filters. The downsides:
* The [autoClose](https://elastic.github.io/eui/#/forms/search-bar#search-bar-filters) property will be ignored and the popover will remain open after a selection, until it is dismissed.
* The selected option is not highlighted in the list
These are deviations from the old behavior but IMO, it's workable until the original issue is fixed.
https://user-images.githubusercontent.com/23465343/192650834-a37eacae-dea5-4fe1-9a14-b1f958d784bb.mov
> Bugfix: Fix tailLines filter for logs viewer

- api/turing/validation/validator.go
- docs/how-to/create-a-router/configure-routes.md
- docs/how-to/create-a-router/configure-traffic-rules.md
- engines/experiment/docs/developer_guide.md
- ui/src/router/components/configuration/components/ExperimentConfigSection.js
- ui/src/router/components/form/components/router_config/GeneralSettingsPanel.js
- ui/src/router/components/form/components/router_config/route_card/RouteCard.js
- ui/src/router/components/form/steps/ExperimentStep.js
- ui/src/router/components/form/validation/schema.js
This MR introduce the following changes 
- some mr comments  in #270
- add the missing remote ui passing of protocol to the Detail page
- add service method for upi routers as form text that is disabled
> Upi UI enhancement 

- api/turing/imagebuilder/imagebuilder.go
Similar to https://github.com/caraml-dev/merlin/pull/553
> fix(image-builder): use google keychain for Artifact Registry domains

- api/go.mod
- api/go.sum
- api/turing/service/ensembling_job_service.go
- api/turing/service/ensembling_job_service_test.go
Remove `job` and add `Ensembler` in the `EnsemblingMonitoringVariables`
> feat: adjust filter for turing monitoring dashboard
