api/turing/service/experiment_service.go, engines/router/missionctl/handlers/internal_api_test.go
PR 64:
Select experiment engine > select a client and one or more experiments > select a different client without clearing the client selection intermediately - API response error from Get Variables, that the experiment id is not found. This happens because the client id is first updated which causes the variables list to refresh (with the new client id and old experiment ids), before the experiment list is updated. This is temporarily fixed in the API by ignoring experiment ids that cannot be found when both client id and experiment ids are set, in the call to get experiment variables.
PR 72:
Check that service URLs are resolvable in the Turing router readiness check. This is to prevent the router from accepting requests before ensembler or enricher hosts are resolvable.
=> Backport internal pull request 64 and 72

api/turing/api/request/request.go, api/turing/api/request/request_test.go, api/turing/config/config.go
Add Experiment field in the Turing API config to allow custom configuration for experiment runners and managers for different experiment engines.
=> Backport internal pull request 79

api/turing/service/experiment_service.go
In the Turing API's `getExperimentsWithCache`, if any experiment id requested is not found, return error.
This method is called by `ListVariables` and this change is a precautionary measure, to have the API return an error if info on any unknown experiment id is requested.
=> Backport internal pull request 81

engines/experiment/manager/types.go
Adding `home_page_url` as an experiment engine property to move this configuration from the UI to the API.
=> Add HomePageURL to Experiment Engine properties

api/turing/middleware/authorization.go, api/turing/middleware/authorization_test.go
Currently, the `allow-all` policy is only defined on the `"resources:mlp:experiment-engines:**"` resource. 
This doesn't cover calls to the root level resource (`"resources:mlp:experiment-engines"`) and this PR is fixing it.
=> [BUGFIX]: update keto policy to allow calls to /experiment-engines

engines/router/missionctl/handlers/http_handler.go, engines/router/missionctl/handlers/http_handler_test.go
Internal MR # 43 changed the Turing router's outcome logging to use the timestamp at the time of response generation, rather than the one generated inside the logging goroutine, which may be delayed. That change introduced a regression since `logTuringRouterRequestSummary` was updated to be called only at the end of all steps, before writing a success response - in cases where one of the steps (Enricher / Router / Ensembler) failed, this method was no longer being called. This PR fixes this regression and adds a unit test case to test the request summary logging.
The changes have been tested on a local router, built from the internal repo.
=> Fix for Regression in Router's Outcome logging when response is unsuccessful

api/turing/api/appcontext.go, api/turing/api/appcontext_test.go, api/turing/service/experiment_service.go, api/turing/service/experiment_service_test.go, engines/experiment/common/web_utils.go, engines/experiment/manager/manager.go, engines/experiment/manager/manager_test.go
`experiment.manager` package is missing:
1. `Register` function  that different experiment managers implementation should call to register themselves.
2. `Get` function that the users of experiment managers should call to retrieve and initialize the registered experiment managers.
This pull request add those 2 functions similar to how they are implemented in `experiment.runner` so experiment runners and managers behaviour is consistent.
https://github.com/gojek/turing/blob/84d3c6bcc1e020d117fc9becbbe4dc88567f3045/engines/experiment/runner/runner.go#L42
https://github.com/gojek/turing/blob/84d3c6bcc1e020d117fc9becbbe4dc88567f3045/engines/experiment/runner/runner.go#L57
Experiment service constructor in `api` module is also updated so that the experiment managers in the service are …
=> Make experiment manager registration and configuration consistent with experiment runner

engines/router/missionctl/fiberapi/fan_in.go
This PR starts a span from the `Aggregate` method in FanIn, to measure the time taken to ensemble the responses.
**Before:**
<hr/>
**After:**
=> Add trace for response ensembling in Turing router's FanIn

api/turing/cmd/main.go, api/turing/config/config.go, api/turing/config/config_test.go
This PR introduces a new env var `ALLOWED_ORIGINS` to the Turing API so that only trusted origins can make requests to the Turing API server via the browser. By default, this value will be set to `*` which is effectively the same as the previous `cors.AllowAll()`.
=> Add env var to set allowed origins for accessing the API server

chart/README.md, chart/templates/deployment.yaml, chart/templates/secrets.yml, chart/values.yaml, test/e2e/turing.helm-values.yaml
Currently Turing Helm chart is missing the default values and documentation about what values can be provided by the user of Helm chart. This makes usage of chart not user friendly.
- This pull request add resonable default Helm values for relevant fields so that the users of the Helm chart does not need to always provide all the values. This will make deployment configuration simpler. 
- Markdown documentation for the Helm values is also provided, using [helm-docs](https://github.com/norwoodj/helm-docs) to render the document.
- Also removed Helm values in `test/e2e/turing.helm-values.yaml` which are already provided by default, in order to simplify configuration
=> Add Turing Helm chart default values and Helm values documentation

engines/router/missionctl/instrumentation/metrics/prometheus.go
This PR changes the Prometheus Histogram buckets defined by the Turing router for capturing custom metrics (request latencies) such that there is more sensitivity at lower values and, at the same time, larger values are accommodated.
=> Change Router Prometheus Histogram buckets

ui/src/router/components/configuration/components/docker_config_section/DockerConfigViewGroup.js, ui/src/router/components/configuration/components/section.scss
This PR fixes a bug in the UI panels where the panel would expand beyond the max screen width when attempting to accommodate a large text.
The problem arises when applying text truncation inside a child flexbox, from the auto-calculated min width of the container exceeding that of the parent which would break the layout. The recommended fix is to set `min-width` to 0 on the child container.
More info: https://css-tricks.com/flexbox-truncated-text/
=> Fix text overflow bug in the UI panels

api/e2e/test/00_all_e2e_test.go, api/e2e/test/testdata/create_router_nop_logger_nop_exp.json.tmpl, api/e2e/test/testdata/create_router_with_traffic_rules.json.tmpl, api/e2e/test/testdata/update_router_high_cpu.json.tmpl
This PR copies the relevant changes from internal MR 92, that attempts to minimize the dependency on Docker Hub, in the internal CI / CD pipelines, due to the recent rate limit imposed by Docker. As a result, the env var `TEST_ECHO_IMAGE` has been added to potentially allow the tests to use a different image (from a different repo), among other changes. However, the image name is set to `kennethreitz/httpbin` by default and no changes are done to the Github pipelines at the moment.
=> Introduce env var TEST_ECHO_IMAGE for API e2e tests

api/e2e/test/helpers_cluster_test.go, api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, api/turing/cluster/knative_service.go, api/turing/cluster/knative_service_test.go
Latest stable version of Knative v0.19 no longer serves apiVersions `v1alpha1` and `v1beta1`.
This PR allows Turing to work with Knative from v0.13 to to least v0.21
https://knative.dev/community/contributing/mechanics/release-versioning-principles/#knative-serving-version-table
=> Update apiVersion for Knative serving from v1alpha1 to v1

api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, ui/src/components/expandable_container/ExpandableContainer.js, ui/src/components/expandable_container/ExpandableDescriptionList.scss, ui/src/router/activity_log/events_list/EventsList.js, ui/src/router/activity_log/events_list/EventsList.scss, ui/src/router/components/configuration/components/section.scss, ui/src/router/history/HistoryView.js
This PR implements the API and UI changes for storing additional info on deployment failures in the DB and displaying them as a part of the `Activity Log` panel in the Turing UI.
When a Knative service fails to deploy within the configured timeout, we attempt to get one of the following logs from the Kubernetes resources, before purging them:
* `user-container` termination message - When a container fails to become ready and the pod repeatedly restarts, the termination message holds the relevant logs ([ref](https://github.com/knative/serving/blob/master/pkg/reconciler/revision/resources/deploy.go#L151))
* Knative service status condition - In cases where the pod was never created (such as bad image name for the user-container), the Knative service's statuses may contain some useful info. …
=> Get additional info on deployment failures

api/swagger.yaml, api/turing/api/request/request.go, api/turing/cluster/servicebuilder/router.go, api/turing/models/log_config.go, api/turing/models/log_config_test.go, api/turing/validation/validator.go, api/turing/validation/validator_test.go
This PR adds the `SerializationFormat` property to the Kafka Config processed by the Turing API, which will allow for setting this value on the Turing Router (implemented in [PR](https://github.com/gojek/turing/pull/31)).
Originally, Kafka result logging was only supported in JSON format. With this change, result logging to Kafka topics can be configured for one of 'json' or 'protobuf' formats.
**Note on DB Migration:**
When these changes are integrated and deployed, the data in the existing Turing database would need to be updated to set `serialization_format: "json"` in the Kafka Config, for the router versions using Kafka as the result logger.
=> Add Serialization property to Kafka Config in Turing API

ui/.env.development, ui/src/config.js, ui/src/router/activity_log/events_list/EventsList.scss, ui/src/router/components/configuration/components/LoggingConfigSection.js, ui/src/router/components/form/components/outcome_config/kafka/KafkaConfigPanel.js, ui/src/router/components/form/validation/schema.js, ui/src/services/router/TuringRouter.js
This PR adds an option to select the message serialization format, from one of 'JSON' and 'Protobuf', for Kafka Result Logging.
The 2 PRs below added support for Protobuf serialization of Kafka messages:
* https://github.com/gojek/turing/pull/31 (Router)
* https://github.com/gojek/turing/pull/32 (API)
This PR updates the UI with the corresponding changes and is the last of them to complete the Protobuf support for Kafka logger.
* `ui/src/router/components/configuration/components/LoggingConfigSection.js` - Display Serialization Format if Kafka logging has been selected
* `ui/src/router/components/form/components/outcome_config/kafka/KafkaConfigPanel.js` - Add `EuiSuperSelect` to choose the serialization formation
* `ui/src/router/components/form/validation/schema.js` - Define the oneOf …
=> UI changes for Kafka Serialization Format selection

.github/workflows/helm-chart.yaml, infra/chart/README.md, infra/chart/requirements.lock, infra/chart/requirements.yaml
Add GitHub action to release Helm chart. Action is based on
https://github.com/helm/chart-releaser-action
On every push to master, if the Helm chart version is updated, a new GitHub release named `turing-chart-VERSION` will be created. The `index.yaml` for the Helm chart repository will also be updated to reflect this new version. The `index.yaml` will be served using GitHub pages. Once merged, this Helm chart repo will be added to https://artifacthub.io (currently the official site for publishing Helm charts)
Example of Turing chart published on staging artifacthub.
https://staging.artifacthub.io/packages/helm/repo1607517787/turing
The requirements.yaml file is removed because currently the postgresql chart dependency is already embedded in this repo so the requirements.yaml file is not …
=> Add GitHub Action for Helm chart release

api/turing/api/appcontext.go, api/turing/config/config.go, api/turing/config/example.yaml, api/turing/models/alert.go, api/turing/models/alert_test.go, api/turing/service/alert_service.go, api/turing/service/alert_service_test.go
This playbook URL will be set as one of the annotations in the alert spec, which can then be used to provide extra information to the alert recipient.
=> Add config to set alert playbook URL

ui/src/components/form/context.js
Pull request https://github.com/gojek/turing/pull/36 updates `react-scripts` package to v4, which enables eslint rule `react-hooks/exhaustive-deps`.
To conform to this rule, this patch is added:
```diff
- const rootHandler = useCallback(new StackableFunction([], handleChanges), [handleChanges]);
+ const rootHandler = useCallback(() => new StackableFunction([], handleChanges), [handleChanges]);
```
But this introduces UI error when editing a router:
This PR updated the patch to use `useMemo` instead of `useCallback`
=> Fix UI error due to invalid type

api/turing/cmd/main.go, api/turing/web/web.go, api/turing/web/web_test.go
Cache busting in React Apps is typically achieved by the following:
* `build/static/` directory with the CSS, Js and other static files contain a hash of the file contents as the file name suffix. This is handled by `npm run build` for the CRA. ([ref CRA doc](https://create-react-app.dev/docs/production-build))
* `index.html` - this file references the static assets and it is advised that this file is not cached, to prevent serving the older versions of an app ([ref Github Issue](https://github.com/facebook/create-react-app/issues/1910))
For the latter, Chrome usually adds the `max-age=0` header in the request, which, although supposed to trigger revalidation, does not guarantee it. Further, navigations in the same browser sessions, usage of forward/back buttons, etc. may not usually …
=> Prevent caching of index.html when API serves the React App

api/db-migrations/000007_log_config_kafka_serialization_format.down.sql, api/db-migrations/000007_log_config_kafka_serialization_format.up.sql
[Recent update](https://github.com/gojek/turing/pull/31) in Turing router add support for multiple Kafka serialization format: json or protobuf
This requires an update to the existing `log_config` data in router version table.  `kafka_config` needs to have `serialization_format` field. This migration ensures that
=> Add data migration script for kafka log config

engines/experiment/runner/types.go, engines/router/missionctl/experiment/interceptors.go, engines/router/missionctl/instrumentation/metrics/prometheus.go
This is so that we can filter / group the experiment metrics by the engine name, experiment name and treatment name for better tracking.
=> Add engine, experiment and treatment labels to experiment Prometheus metrics in router

ui/src/services/version/RouterVersion.js
The comparison of docker ensemblers in Version Deff View was working incorrectly, because the wrong schema of `ensembler` JSON object was used in `toPrettyYaml` method. This is fixed now
=> [BugFix] Fix version comparison of docker ensemblers

ui/src/hooks/useMonitoring.js
The placeholder for "any" revision in the monitoring dashboard should be `$__all`, instead of `$_all`
=> [BugFix] fix monitoring link when no specific revision is selected

infra/chart/Chart.yaml
In the [previous MR](https://github.com/gojek/turing/pull/60), the Helm chart of Turing was changed, however the version of it remained the same. This resulted in the [failure](https://github.com/gojek/turing/actions/runs/897393012) of the Github workflow, caused by the fact, that Git tag with the current version already exists in the repo. 
This is an expected behaviour of [chart-releaser-action](https://github.com/helm/chart-releaser-action), because it checks the diff of the chart itself and creates a new Github release whenever the changes are detected. If release with the same chart version already exists, then this translates into an observed failure. Meaning, that Chart's version should always be updated if chart files were changed.
=> Bump version of Turing's chart

api/turing/cmd/main.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/example.yaml, infra/chart/Chart.yaml
New Relic integration has been put added to wrap all handlers, but the init component has not been run, therefore it was not pushing to New Relic. This PR adds the initialisation of New Relic.
=> Add New Relic integration.

.github/workflows/engines-batch-ensembler.yaml
I forgot master branch is now called main in Github. This fixes the builds for the ensembling job that are supposed to be for main branch.
=> Fix: Change building of ensembler image from master branch to main.

infra/chart/Chart.yaml
The migrations are failing in newer installs because the DB migrations are not in sync. This will update the chart versions so that db migrations are in sync with the codebase.
=> Bump version of Turing charts.

api/db-migrations/000009_ensembling_job.up.sql, api/openapi.yaml, api/openapi/jobs.yaml, api/turing/api/ensembling_job_api.go, api/turing/api/ensembling_job_api_test.go, api/turing/batch/ensembling/controller.go, api/turing/batch/ensembling/controller_test.go, api/turing/batch/ensembling/mock_ensembling_controller.go, api/turing/batch/ensembling/runner.go, api/turing/batch/ensembling/runner_test.go, api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, api/turing/cluster/mocks/controller.go, api/turing/imagebuilder/imagebuilder.go, api/turing/imagebuilder/imagebuilder_test.go, api/turing/imagebuilder/mocks/image_builder.go, api/turing/models/ensembling_job.go, api/turing/service/ensembling_job_service.go, api/turing/service/ensembling_job_service_test.go, api/turing/service/mocks/ensembling_job_service.go
This PR adds the `DELETE` `/projects/{project_id}/jobs/{id}` to terminate a job.
The API accepts a request to delete the record and sets the status to `terminating`. The batch runners will periodly check if it is time to delete the associated Kubernetes resources (Job and SparkApplication) before physically deleting the record from the database.
Checks have to be done at different stages of the orchestration process, making sure that is no race conditions (I have tested this extensively) during the termination process and building process.
=> Terminate ensembling job

infra/chart/Chart.yaml
Version bump required for the helm chart release due to the changes in db schema for the termination job.
Changes here: https://github.com/gojek/turing/pull/69/files#diff-fad116ed944370b59b28aea03d283195dc2cb1c304fdaf0d087de781501407cfR6
=> Bump version for Termination job.

api/openapi/jobs.yaml, api/turing/api/ensembling_job_api.go, sdk/requirements.txt, sdk/samples/batch_job/batch_job.py, sdk/tests/__init__.py, sdk/tests/batch/job_test.py, sdk/tests/conftest.py, sdk/tests/ensembler_test.py, sdk/tests/fixtures/mlflow.py, sdk/tests/testdata/api_responses/get_job_0000.json, sdk/turing/__init__.py, sdk/turing/_base_types.py, sdk/turing/batch/job.py, sdk/turing/ensembler.py, sdk/turing/generated/api/ensembling_job_api.py, sdk/turing/generated/model/ensembler_job_status.py, sdk/turing/project.py, sdk/turing/session.py
This PR builds up on the [previous PR](https://github.com/gojek/turing/pull/72) and adds the way to terminate a running job from the SDK
- Added `.terminate()` and `.refresh()` methods into `EnsemblingJob`class
- Added minor fixes into turing-api and openapi spec
- Extended [batch_job.py](https://github.com/gojek/turing/compare/main...romanwozniak:sdk_terminate_ensembling_job?expand=1#diff-24411c64b2ce258f7ecccd88cb035d695dbc0e652fba7025ddc156d26117a620) example with a demonstration on how to terminate the job
- Unit tests
=> Turing SDK: terminate ensembling job

README.md, api/config-dev.yaml, api/turing/api/appcontext.go, api/turing/api/appcontext_test.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/example.yaml, api/turing/models/ensembling_job.go, api/turing/service/ensembling_job_service.go, api/turing/service/ensembling_job_service_test.go, test/e2e/turing.helm-values.yaml
This PR adds the following:
1. Default Spark config annotations that is configurable in the Turing API config file.
2. Add in validation for the Create ensembling job POST body.
3. Nasty side effects include the rewiring of viper configuration delimiter from `.` to `::` due to a problem in unmarshalling strings.
For example:
```go
type Foo struct {
Bar map[string]string
}
```
with a configuration of
```yaml
Foo:
Bar:
"hello.one.two": "some string"
```
Will yield this structure instead:
```foo
Foo = interface{}{
"Bar": interface{}{
"hello": interface{}{
"one": inteface{}{
"two": "some string",
},
},
},
}
```
To solve this, we change the delimiter to something uncommon, say a cons operator `::`.
=> Add validation and default ensembling job values.

engines/batch-ensembler/Dockerfile, engines/batch-ensembler/entrypoint.sh
Turns out the Entrypoint must be overriden in order to ensure backward compatibility with a older controller. In this situation, it is impossible to downgrade the spark docker version because the ensembler uses the newer features in the newer versions of Python. This fix ensures that the `driver-py` argument is caught. Or else this error will appear:
```
++ id -u
+ myuid=185
++ id -g
+ mygid=100
+ set +e
++ getent passwd 185
+ uidentry=spark:x:185:100:,,,:/home/spark:/bin/bash
+ set -e
+ '[' -z spark:x:185:100:,,,:/home/spark:/bin/bash ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' 3 == 2 ']'
+ '[' 3 == 3 ']'
++ python3 -V
+ pyv3='Python 3.8.10'
+ export …
```
=> Ensure ensembler image is compatible with old spark controller.

api/api/specs/jobs.yaml, api/turing/service/ensembling_job_service.go, ui/package-lock.json, ui/package.json, ui/src/App.js, ui/src/ensembler/list/ListEnsemblersTable.js, ui/src/ensembler/list/ListEnsemblersView.js, ui/src/job/list/ListEnsemblingJobsTable.js, ui/src/job/list/ListEnsemblingJobsView.js, ui/src/providers/ensemblers/context.js, ui/src/services/ensembler/EnsemblerType.js, ui/src/services/enum/Enum.js, ui/src/services/enum_value/EnumValue.js, ui/src/services/job_status/JobStatus.js, ui/src/services/status/Status.js
This PR makes it possible to view a list of ensemblers in Turing UI. Plus:
* Makes it possible to view ensembling jobs of a specific ensembler
* Updates jobs api to support `ensembler_id` and `search` query parameters
* Bumps version of `@mlp/ui` library to use the newer version of `NavDrawer`
=> UI: Add view to show ensemblers

.github/workflows/e2e.yaml, .github/workflows/swagger.yaml, api/api/Dockerfile, api/api/Makefile, api/docker-compose.yaml, api/turing/cmd/main.go, engines/router/compose/docs.yaml, infra/chart/Chart.yaml, infra/chart/templates/deployment.yaml, infra/chart/values.yaml, test/e2e/setup-infra.sh, test/e2e/turing.helm-values.yaml
Previously, the refactoring of swagger yaml files have been split up and the process of how the yaml files were transferred to the SwaggerUI running container was not updated. As a result, SwaggerUI is not able to serve the openapi specs correctly.
This PR changes how SwaggerUI is built and deployed. A custom image will be built on top of SwaggerUI's Docker image to populate the openapi yaml files and deployed alongside with the Turing API pod.
Test for Docker build is here: https://github.com/gojek/turing/runs/3308105094?check_suite_focus=true, temporarily removed the guard for main branch only, will be reenabling that. I do not have the credentials so the pushing to GHCR will fail.
=> Fix Swagger UI in Helm chart.

README.md, api/config-dev.yaml, api/turing/api/appcontext.go, api/turing/api/appcontext_test.go, api/turing/batch/ensembling/controller_test.go, api/turing/batch/ensembling/runner.go, api/turing/batch/ensembling/runner_test.go, api/turing/batch/runner/base.go, api/turing/cluster/spark.go, api/turing/cluster/spark_test.go, api/turing/cmd/main.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/example.yaml, api/turing/imagebuilder/ensembler.go, api/turing/imagebuilder/imagebuilder.go, api/turing/imagebuilder/imagebuilder_test.go, test/e2e/turing.helm-values.yaml
Added a toggle to turn off the batch ensembling feature.
By design, the API binary will panic if the wrong configurations are given. If the user requires the batch ensembling feature, he should be confident that it should work when it is deployed. As opposed to only finding out the problem when the feature is being used.
Small bug I found in the configuration regarding Kubernetes Tolerations: fixed by using the correct key and remove TaintKey as it is redundant.
=> Add a feature toggle to disable batch ensembling runners

api/go.mod, api/go.sum, api/turing/middleware/openapi_validation.go, api/turing/middleware/openapi_validation_test.go
This PR updates the `getkin/kin-openapi` library version used by the Turing API to the latest at `v0.75.0`. This is required because the internal Turing repo's dependencies use a newer version of the same library which causes conflicts.
=> Update OpenAPI library version

api/api/specs/ensemblers.yaml, api/api/specs/jobs.yaml, api/db-migrations/000009_ensembling_job.up.sql, api/turing/models/ensembling_job.go, api/turing/models/pyfunc_ensembler.go, api/turing/service/ensembling_job_service.go, api/turing/service/ensembling_job_service_test.go, infra/chart/Chart.yaml
As requested from this [thread](https://github.com/gojek/turing/pull/87#discussion_r694403174) we are supplying a `run_id` to give ensembling jobs more sane and shorter names.
=> Add RunID Generation for ensembling jobs.

api/turing/service/ensembling_job_service.go
As pointed out in the comments, `GetResources` returns a copy of the resources object and not a pointer. So it has to be set back into the InfraConfig
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a0b5ff]
goroutine 2109 [running]:
github.com/gojek/turing/api/turing/batch/ensembling.(*ensemblingController).createSparkApplication(0xc000a6fef0, 0xc001393c50, 0xc000fede40, 0x10, 0x0, 0x0)
/app/vendor/github.com/gojek/turing/api/turing/batch/ensembling/controller.go:194 +0x35f
github.com/gojek/turing/api/turing/batch/ensembling.(*ensemblingController).Create(0xc000a6fef0, 0xc001393c50, 0x0, 0x0)
/app/vendor/github.com/gojek/turing/api/turing/batch/ensembling/controller.go:166 +0x781 …
```
=> Fix nil pointer when accessing resources.

ui/src/router/details/components/router_details_header/RouterDetailsPageHeader.js
This PR addresses edge cases from https://github.com/gojek/turing/pull/115
* Show the router timeout value only if available (new routers would not have a `config` property)
* Show "Not available" in place of router timeout if it is currently updating (rationale: when the router is updating, it is not clear if this value belongs to the new config or old config).
=> Display router timeout if available

api/turing/api/appcontext.go, api/turing/api/appcontext_test.go, api/turing/middleware/authorization.go, api/turing/middleware/authorization_test.go, api/turing/server/application.go, ui/src/router/components/configuration/RouterConfigDetails.js, ui/src/router/components/configuration/components/ExperimentConfigSection.js, ui/src/router/components/configuration/components/TreatmentMappingConfigSection.js, ui/src/router/components/configuration/components/config.js, ui/src/router/components/configuration/components/experiment_config_section/ExperimentConfigGroup.js, ui/src/router/components/configuration/components/experiment_config_section/credentials/CredentialsConfigSection.js, ui/src/router/components/configuration/components/experiment_config_section/experiments/ExperimentsConfigTable.js, ui/src/router/details/config/RouterConfigView.js, ui/src/router/versions/details/RouterVersionDetailsView.js, ui/src/router/versions/details/config/RouterVersionConfigView.js
This PR makes some minor modifications.
1. In an earlier [PR](https://github.com/gojek/turing/pull/103), the set up of the HTTP handler was refactored. The usage of the [Subrouter](https://pkg.go.dev/github.com/gorilla/mux#Route.Subrouter) with [PathPrefix](https://pkg.go.dev/github.com/gorilla/mux#Router.PathPrefix), however, broke the expectation within the Authorization Middleware, causing the resources to be formatted as `v1:projects:{id}:*` as opposed to `projects:{id}:*`. This MR propagates the API handler's path prefix to the Authorization middleware upon initialisation, so it can be ignored at the time of validation.
2. The UI now allows a templated string to be supplied by the experiment engine, for its `home_page_url` property so that the template `{{projectId}}` in the string …
=> Handle API path prefix in Authorization Middleware, allow templated Experiment Engine Homepage URL

.github/workflows/turing.yaml, infra/charts/turing-init/Chart.yaml, infra/charts/turing-init/README.md, infra/charts/turing-init/templates/cleanup-job.yaml, infra/charts/turing-init/templates/cluster-role.yaml, infra/charts/turing-init/templates/init-job.yaml, infra/charts/turing-init/templates/istio-operator-config-map.yaml, infra/charts/turing-init/values.yaml, infra/cluster-init/init.sh
This PR allows some extra configuration of the Knative service during the provisioning of third party software handled by the turing-init chart:
1. Allow extra Knative domains to be used
2. Allow custom container registries to be used.
This flow is tested using the e2e test flow.
=> Add more Knative configs into turing-init for the setting up of Turing's infrastructure

ui/package.json, ui/yarn.lock
Since our internal Experiment-Engine (EE) UI requires the use of Drag-And-Drop component from `eui` library which has dependency on `react-beautiful-dnd`, an issue as described in this [PR](https://github.com/gojekfarm/react-beautiful-dnd/pull/1) was found and needs to be resolved, by using the fix introduced (via module resolution).
Module resolution is required on Turing because it uses the same `eui` version as the EE (`32.3.0`). In the scenario where the EE uses a different minor/patch version, the change introduced in this PR will not be required since the dependency is not a singleton. Validation has been done and this behaviour is consistent with our conclusion in previous PR: #114 .
Regardless, this module resolution fix will be useful if Turing-UI starts using Drag-And-Drop …
=> Add module resolution for react-beautiful-dnd

ui/src/router/details/components/page_navigation/RouterDetailsPageNavigation.js
Regression from: https://github.com/gojek/turing/pull/121
Should check app's alert configs and not the router version's. The version does not have an 'alert' field.
=> Bugfix: Change condition for alert tab display

ui/src/components/horizontal_description_list/HorizontalDescriptionList.js, ui/src/router/components/router_endpoint/RouterEndpoint.js, ui/src/router/details/components/router_details_header/RouterDetailsPageHeader.scss
**View before fix**
**View after fix**
This PR fixes:
- Overflow of elements when window size is small
- Abruptly truncated endpoint
=> Fix Router details UI overflow

api/api/specs/experiment-engines.yaml, api/go.sum, engines/experiment/manager/types.go, ui/src/router/components/configuration/components/experiment_config_section/credentials/CredentialsConfigSection.js, ui/src/router/components/form/components/experiment_config/typeOptions.js
Adding the `DisplayName` field to the engine props that can be utilised in the Turing UI instead of the `Name`, if set by the experiment engine.
* `engines/experiment/manager/types.go` - Add `DisplayName` property
* `ui/src/router/components/form/components/experiment_config/typeOptions.js` - Use display name in router configuration form
* `ui/src/router/components/configuration/components/experiment_config_section/credentials/CredentialsConfigSection.js` - Use display name in router details view
=> Add optional DisplayName in Experiment Engine props

ui/src/router/components/configuration/components/EnsemblerConfigSection.js, ui/src/router/components/configuration/components/TreatmentMappingConfigSection.js, ui/src/router/details/components/RouterActions.js, ui/src/router/versions/details/config/RouterVersionConfigView.js
* Error on historical Router Version view - Missing `ExperimentEngineContextProvider` around the view
* Standard Ensembler config panel - Engine props passed down was `{}`, needed to read from Experiment Engine context
* Router action `Undeploy` should also be hidden for `Failed` router status
=> Fix minor UI bugs

api/e2e/test/01_create_router_test.go, api/turing/cluster/servicebuilder/router.go, api/turing/cluster/servicebuilder/router_test.go, api/turing/cluster/virtual_service.go, api/turing/cluster/virtual_service_test.go, engines/router/missionctl/cmd/main.go, engines/router/missionctl/handlers/batch_http_handler.go, engines/router/missionctl/handlers/batch_http_handler_test.go, engines/router/missionctl/handlers/http_handler.go, engines/router/missionctl/testdata/batch_router_test.yaml, engines/router/missionctl/turingctx/context.go, engines/router/missionctl/turingctx/context_test.go
This PR will add a new endpoint, `batch_predict` to Turing router. 
Currently the individual request are handled async. Individual request will behave the same as current state (no retries). 
Individual request failures will not fail the entire request and be lodged as part of the response.
Current batch endpoint expects "batch_request" with an array of requests and will return a response with "batch_result" with the array of response with fields `code`, `error`, `data`. 
Sample request
Sample response
`api/e2e/test/01_create_router_test.go` - Add batch_endpoint testing to e2e test
`api/turing/cluster/servicebuilder/router.go` - Change string to []string, to add batch_endpoint prefix to default
`api/turing/cluster/virtual_service.go` - Loop through prefixes to add multiple matches if …
=> Batch predict endpoint

README.md, infra/charts/turing-init/README.md, infra/charts/turing-init/README.md.gotmpl, infra/charts/turing/README.md, infra/charts/turing/README.md.gotmpl
The instructions for the turing-init chart was outdated as it was not published to the public repository then.
=> Update documentation on Turing Init.

README.md, infra/charts/turing-init/README.md, infra/charts/turing-init/README.md.gotmpl
Added some port requirements that needs to be allowed to the nodes from the master so that knative serving and spark operator mutating webhooks in the readme.
=> Add instructions on ports that needs to be reachable from master.

engines/router/missionctl/experiment/interceptors.go, engines/router/missionctl/instrumentation/metrics/prometheus.go
This PR removes the experiment and treatments for experiment engine metrics.
The flexibility to allow experiment engine to log additional labels which might cause a huge cardinality. 
Also, it is recommended not use dimensions with high cardinality - 
https://prometheus.io/docs/practices/naming/
https://www.robustperception.io/cardinality-is-key
```
CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, 
which can dramatically increase the amount of data stored.
Do not use labels to store dimensions with high cardinality (many different label values), 
such as user IDs, email addresses, or other unbounded sets of values.
```
=> Removing experiment and treamtent labels from experiment engine metrics

.github/actions/build-cluster-init/action.yaml, .github/actions/cluster-init/action.yaml, .github/actions/run-cluster-init/action.yaml, .github/workflows/cluster-init.yaml, .github/workflows/turing.yaml
Refactor existing Turing CI workflow, to remove tear down of cluster and do it as an e2e test part of cluster-init workflow.
`.github/actions/cluster-init/action.yaml` - New github action to be called by both Turing and cluster-init workflow to init the cluster. It will contain inputs to optionally build an image or to use an built jar.
The steps involved are:
1. Setup k3d cluster
2. (Optional) Build and save Cluster-Init Image
3. Push image to local registry
4. Install cluster
`.github/workflows/cluster-init.yaml` - Updated to include an e2e test.
Steps
1.  Trigger `cluster-init` github action 
2. Deploy an knative service for smoke test
3. Tear down infra
`.github/workflows/turing.yaml` - Extracted installation of cluster as github action and to call the action instead. Removed tearing …
=> Update ci teardown to cluster init

Dockerfile, api/api/Makefile, api/api/openapi.bundle.yaml, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/server/application.go, api/turing/server/static.go, api/turing/utils/merge.go, scripts/swagger-ui-generator/swagger-ui-generator.sh
The main motivation for this PR is that whenever we deploy our application, swagger-ui is [referencing a fixed URL for openapi.bundle.yaml](https://github.com/gojek/turing/blob/1de5d8397d885d8342fc71b9a477a034c9d4a885/scripts/swagger-ui-generator/swagger-ui-generator.sh#L136), which does not allow for any URL rewrites when using a reverse proxy. Letting Swagger UI handle it based on file names allows the use of relative paths (which can be manipulated by a reverse proxy) rather than fixed static paths.
=> Allow Swagger UI to use file instead of serving it on a URL

Dockerfile, Makefile
Cherry picked from @romanwozniak to fix the docker builds. Turing API was not able to write to the swagger ui folder because the permissions were tied to root rather than the turing user.
Since the CI doesn't cover this, I have built and tested the image locally.
=> Fix turing docker

engines/batch-ensembler/Dockerfile
The current batch ensembler Dockerfile uses Debian 10 (Buster), which has recently (14/8/2021) been superseded by Debian 11 (Bullseye). With Bullseye now becoming the new `stable` release, Buster has been relegated to `oldstable`. This forces the `apt-get update` command [here](https://github.com/gojek/turing/blob/main/engines/batch-ensembler/Dockerfile#L34) to require an explicit approval which terminates the Docker image building process.
This PR introduces an addition of a flag to ignore the `oldstable` release in the update command. This is only a temporary fix while support for Buster remains supported.
- `turing/engines/batch-ensembler/Dockerfile` - addition of a `--allow-releaseinfo-change-suite` flag to the `apt-get update` command
=> Fix batch ensembler Dockerfile

sdk/setup.py, sdk/turing/batch/config/config.py
Turing SDK currently supports Python 3.8 and above. In order to accommodate a larger variety of plugins/packages/libraries/etc., we're expanding support of Turing SDK to Python 3.7 and above.
- `sdk/turing/batch/config/config.py` - add checks to ensure that `env` used to initialise a `EnsemblerInfraConfig` is an empty list if `env_vars` is returned as `None`
- `sdk/setup.py` - replace Python requirement from `>=3.8` to a more general `>=3.7`
=> Add Python 3.7 support

sdk/turing/ensembler.py
Turing SDK offers an abstract class `PyFunc` from which the concrete `PyFuncEnsembler` is implemented. In particular, this `PyFunc` class implements the abstract method `predict` from its parent `mlflow.pyfunc.PythonModel`, which gets called whenever the `mlflow` model is used to generate predictions (or in this case, ensembling results).
This `predict` method partially implements the batch ensembling logic, i.e. it performs some simple `DataFrame` manipulations by separating a single input `DataFrame` into `DataFrames` corresponding to `features`, `predictions` and `treatment_config`, that subsequently get passed to a user-defined `ensemble` method, which contains the rest (and the crux) of the ensembling logic.
Previously, the `treatment_config` field has always been unused, since in …
=> Update abstract PyFunc to utilise returned treatment_config

engines/router/missionctl/handlers/http_handler.go
Issue: https://github.com/gojek/turing/issues/166
* Knative adds the `Accept-Encoding: gzip` header  to each proxied request in all versions before 0.21.x (this behaviour was changed in v0.21: https://github.com/knative/serving/pull/10691)
* Becasue if this, even if a client has sent a request without asking to compress the response, the requests to all internal components (such as routes, enricher, ensembler) will be made with `Accept-Encoding: gzip`, and if any of these components supports compression – the response will be gzipped
* Before sending the response back to the client, Knative looks if the request is compressed (response headers contain `Content-Encoding: gzip`) and decodes it accordingly
* But Turing router doesn't propagate headers from the ensembler, hence …
=> Fixes #166 [router] Return all response headers unmodified

engines/experiment/config/config.go, engines/experiment/config/config_test.go, engines/experiment/factory.go, engines/experiment/factory_test.go, engines/experiment/go.mod, engines/experiment/go.sum, engines/experiment/plugin/inproc/factory.go, engines/experiment/plugin/inproc/factory_test.go, engines/experiment/plugin/rpc/factory.go, engines/experiment/plugin/rpc/factory_test.go, engines/router/Makefile, engines/router/go.sum
Turing supports [Traffic Rules](https://github.com/gojek/turing/blob/main/docs/how-to/create-a-router/configure-traffic-rules.md) via Fiber's [LazyRouter](https://github.com/gojek/fiber/blob/main/lazy_router.go), where each route in this LazyRouter is another Fiber component (either [EagerRouter](https://github.com/gojek/fiber/blob/main/eager_router.go) (when standard or no ensembler is used) or [Combiner](https://github.com/gojek/fiber/blob/main/combiner.go) (when Docker ensembler is used)). The configuration of each route contains all the information that this traffic rule's route requires, including the routes activated when this traffic rule is matched and the configuration of the experiment engine, if it's configured on the router. The entire configuration could look something like …
=> [BUGFIX] Fix experiment engine plugins in routers with the traffic rules 

api/turing/api/request/request.go, api/turing/api/request/request_test.go, api/turing/cluster/servicebuilder/router.go, api/turing/cluster/servicebuilder/router_test.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/testdata/config-2.yaml, api/turing/models/log_config.go, api/turing/models/log_config_test.go, engines/router/missionctl/config/config.go, engines/router/missionctl/config/config_test.go, engines/router/missionctl/log/resultlog/kafka.go
This MR is a follow up from the [previous](https://github.com/gojek/turing/pull/172), it allows
`max.request.size` and `compression.type` of the Kafka producer configuration to be set in helm values when deploying Turing Server.
`api/turing/api/request/request.go` - Appended `MaxMessageBytes` and `CompressionType` during building of new router version when logger type is kafka.
`api/turing/cluster/servicebuilder/router.go` - Creating router with env var `APP_KAFKA_MAX_MESSAGE_BYTES` and `APP_KAFKA_COMPRESSION_TYPE`
`engines/router/missionctl/log/resultlog/kafka.go` - Router's logger to init with config, which are read from env var during initialisation.
Setting router default in Turing Server helms value
Router container env var set with the global values
=> Set kafka message size and compression as configurable

engines/router/missionctl/handlers/http_handler.go
This PR introduces a minor change to merge the headers of the original request sent to Turing routers with that of the response returned from an enricher.
This in effect parses the enricher response headers for downstream traffic rules and experiment input, but *does not* parse them for ensembling.
- `engines/router/missionctl/handlers/http_handler.go` - Addition of a few lines of code to merge the headers of the original request and enricher response
=> Add steps to merge original request and enricher response headers

sdk/turing/router/config/experiment_config.py, sdk/turing/router/config/router_ensembler_config.py, sdk/turing/router/router.py
This update to the Turing SDK adds commits to the existing release of Turing SDK (`v0.2.0`), which serve to introduce a `version` attribute in the `Router` SDK. This `version` attribute (as well as a router's other attributes) gets updated when `wait_for_status` gets called on a `Router` instance. When `wait_for_status` returns successfully, the `version` attribute would be expected to contain the current router version number. 
This update is mainly targeted at scenarios when one updates a router - right after calling `update`, the existing router version that is deployed remains the same while the new version enters the `pending` state. Instead of having to query the status of the Router actively in order to retrieve the new router version id when it has finally been deployed …
=> Add wait for status update

ui/src/router/components/form/components/pyfunc_config/PyFuncDeploymentPanel.js
This PR introduces a tiny fix to the UI to correct the size of the pyfunc ensembler deployment panel from large to small.
=> Set EUI spacer to small

api/e2e/test/01_create_router_test.go, engines/experiment/examples/plugins/hardcoded/go.mod, engines/experiment/examples/plugins/hardcoded/runner_test.go
https://github.com/gojek/turing/pull/184 contained the updates to the e2e tests to cover the deployment of a Turing Router with the experiment engine plugin. It turned out, that one of the tests started failing intermittently because of the non-deterministic behavior (https://github.com/gojek/turing/pull/188#discussion_r835065627).
The problem occurs only with the test, that asserts the `/batch_predict` endpoint response. Previously, the request payload to the `/batch_predict` contained two equal prediction request payloads (the entire request was `[{}, {}]`), however, https://github.com/gojek/turing/pull/184 has changed this to verify that the experiment engine assigns treatments correctly to different requests. 
I'm not able to verify, that the experiment engine assigns treatments …
=> [BUG] Fix End-to-End test suite 

.github/workflows/pyfunc-ensembler-job.yaml, .github/workflows/pyfunc-ensembler-service.yaml, .github/workflows/sdk.yaml, sdk/turing/router/router.py, ui/src/components/config_section/index.scss, ui/src/router/components/configuration/components/docker_config_section/ContainerConfigTable.js
With the PR #188, the Python versions for the Turing SDK as well as both ensembler engines have been fixed at `3.7.*`. While these changes have been made on these components, the workflows for these components have not been updated yet.
This PR serves to update these workflows to utilise Python 3.7 accordingly.
- Tiny fix to the Turing SDK to handle cases whereby `RouterConfig` is not returned as part of a response body containing Routers
- Tiny fix to the Turing UI to allow for text wrapping when the docker image name is too long
=> Update workflows to use Python 3.7 for ensembler engines and sdk

infra/charts/turing/Chart.yaml, infra/charts/turing/README.md, infra/charts/turing/templates/_helpers.tpl, infra/charts/turing/values.yaml
This PR makes the following 2 minor fixes to the helm chart:
* `infra/charts/turing/values.yaml` - The default value for the `experimentEngines` should be a map rather than a list, as it is processed so. Having `{}` as the default would cause the following warnings during a helm install:
```
coalesce.go:200: warning: cannot overwrite table with non table for experimentEngines (map[])
```
* `infra/charts/turing/templates/_helpers.tpl` - When an experiment engine is registered but the `options` are unset (either the key does not exist or the value is an empty map `{}`), the `{{ toYaml $expEngine.options | indent 4 }}` causes problems with the indentation of other lines:
```
Error: 'error converting YAML to JSON: yaml: line 32: mapping values are not allowed
in this context'
```
This is …
=> Minor fixes for experiment engine configs in the helm chart

sdk/tests/conftest.py, sdk/tests/router/config/router_config_test.py, sdk/tests/router/config/router_ensembler_config_test.py, sdk/turing/router/config/router_config.py, sdk/turing/router/config/router_ensembler_config.py, ui/src/services/ensembler/PyFuncEnsembler.js, ui/src/services/router/TuringRouter.js
This MR fixes a few minor bugs on the UI / SDK.
* `ui/src/services/router/TuringRouter.js` - When a router with No Ensembler / Standard Ensembler is edited and updated to use Custom Ensembler (docker / pyfunc), the `default_route_id` property from the previous configs should be dropped before calling the API. (We could drop this as soon as the type of the Ensembler is changed from the UI but we don't do this for other components too, because with that approach, if the user switched back to the old type in the same edit session, we would have lost the values.)
* `ui/src/services/ensembler/PyFuncEnsembler.js` - Fix regression around missing container config display for Pyfunc ensemblers. Since the detail views now use the parsed data, including the `docker_config` when parsing.
Under the …
=> Bugfix: Clear default route Id from custom ensembler configs

infra/charts/turing/Chart.yaml, infra/charts/turing/values.yaml
Update Helm chart for Turing app release `v1.5.0`
=> Update chart version for app release

ui/.env, ui/src/config.js, ui/src/experiment/ExperimentsRouter.js, ui/src/hooks/useDynamicScript.js
**What this PR does / why we need it:**
This PR is required to dynamically load any global variables from configured Experiment Engine UI via script tag in Turing's index.html file. This can be done through providing the url of the config, similar to how the url of the UI is provided currently.
**Which issue(s) this PR fixes:**
`NONE`
=> Add dynamic loading of Experiment Engine config

ui/src/components/experiments/ExperimentEngineLoaderComponent.js, ui/src/components/remote_component/DynamicHookComponent.js, ui/src/experiment/ExperimentsRouter.js, ui/src/hooks/useDynamicScript.js, ui/src/router/components/configuration/components/ExperimentConfigSection.js, ui/src/router/components/form/components/experiment_config/ExperimentConfigPanel.js
**What this PR does / why we need it:**
A previous related [PR](https://github.com/gojek/turing/pull/202) caused a bug which crashes Routers Details view. This view uses `ExperimentConfigSection` component which requires configured Experiment Engine information retrieved via global variables configured on the Experiment Engine UI. This resulted in runtime configs being NOT loaded into the index.html headers and hence, not available for use.
Logs show the following information:
```
TypeError: Cannot read properties of undefined (reading 'experimentEngineApiUrl')
...
```
This PR addresses the above issue for both `ExperimentConfigSection` and `StandardExperimentConfigGroup` components which load information from the remote Experiment Engine UI.
=> Fix dynamic loading of Experiment Engine config

engines/experiment/manager/types.go
**What this PR does / why we need it:**
In relation to previous [PR](https://github.com/gojek/turing/pull/205), `config` field is now optionally used by the UI to dynamically load shared state via a remote entry file and this is required on RemoteUI struct for Experiment Engine plugin as well to be used.
=> Add missing config field to RemoteUI struct

ui/src/router/alerts/details/RouterAlertDetails.js
This PR is a small fix for a regression introduced by https://github.com/gojek/turing/pull/192, which introduced conversion of the API router / router version response to `TuringRouter` and `RouterVersion` objects, respectively, before passing down to the views. Thus, the conversion of the status string to the `Status` object would have also happened ahead of time and there is no need to do `Status.fromValue` within the `RouterAlertDetails` component. This was missed in the original PR.
=> Bugfix: Show Configure Alerts button when router is deployed

api/turing/cluster/knative_service.go, api/turing/cluster/knative_service_test.go
In recent versions of Knative, the private resources must be created with the `networking.knative.dev/visibility=cluster-local` label which was previously `serving.knative.dev/visibility=cluster-local`. See:
* https://github.com/knative/serving/blob/knative-v1.0.1/config/core/configmaps/domain.yaml#L58
* https://knative.dev/v1.2-docs/serving/services/private-services/
Without the right label, the Enrichers and Ensemblers will have both sets of hosts mapped (cluster-local and external-ip).
In https://github.com/gojek/turing/pull/207, the Knative `net-istio` controller (used in e2e tests) was upgraded to `1.0.0`. The same version of the controller is used internally in Gojek, to run e2e tests against a GKE cluster. The tests were proving to be flaky with both the routers (accessed via the …
=> Fix cluster-local annonation, set knative svc defaults

ui/src/components/experiments/ExperimentEngineLoaderComponent.js
When a custom experiment engine's remote UI must be loaded, the current implementation of the `ExperimentEngineLoaderComponent` loads the remote entry file first and then the dynamic config, if any, sequentially. If both succeed, the children of the component (which would attempt to load the specific remote components from the remote engine UI) will be returned. Intermittently, the config loader fails to be mounted with the following warning:
As a result, the experiment engine's dynamic configs are not loaded which causes unexpected behaviours in the respective views - this can only be reset with a hard refresh. As an example, we see the below error with the [turing-experiments](https://github.com/gojek/turing-experiments) engine, when viewing a router (the API host, which was supposed to …
=> Fix experiment engine dynamic config load

api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, api/turing/cluster/mocks/controller.go, api/turing/service/router_deployment_service.go, api/turing/service/router_deployment_service_test.go
Turing's dependency on Kubernetes API was updated in https://github.com/gojek/turing/pull/183 and most Kubernetes APIs now require context to be passed which caused a regression. When [ctx.Done()](https://github.com/gojek/turing/blob/main/api/turing/cluster/controller.go#L721) is called, the context was cancelled and ctx.Err() returns a non-nil error. Thus, when passed to [ListPods API](https://github.com/gojek/turing/blob/main/api/turing/cluster/controller.go#L751), when the ctx.Err() value is first checked, the call exits given a non-nil error and pods that satisfy the provided labels are never returned, causing termination logs to NOT be propagated to the user.
The fix uses a new empty context via context.Background(), which will not be cancelled and that allows Kubernetes Go Client …
=> Use background context rather than cancelled context

docs/how-to/create-a-router/configure-ensembler.md, engines/pyfunc-ensembler-service/pyfunc_ensembler_runner/ensembler_runner.py, engines/pyfunc-ensembler-service/pyfunc_ensembler_runner/handler.py, engines/pyfunc-ensembler-service/tests/conftest.py, engines/pyfunc-ensembler-service/tests/test_ensembler_runner.py, engines/router/missionctl/handlers/http_handler.go, engines/router/missionctl/handlers/http_handler_test.go, sdk/samples/common/__init__.py, sdk/samples/router/create_router_with_pyfunc_ensembler.py, sdk/turing/ensembler.py
This PR makes 2 user-facing changes:
* `engines/router/missionctl/handlers/http_handler.go` - Make the Enricher's response headers available to the Ensembler in the request headers. The merging of the headers was introduced in https://github.com/gojek/turing/pull/176, intended to be used for the routing step and we hadn't propagated it down to the Ensembler. However, allowing the Ensembler access to those values would help the Ensembler make decisions based on values computed by the Enricher.
* Pass request headers to the Pyfunc Ensembler. Previously, request headers were not available to Pyfunc ensemblers. The changes are described in detail below.
To support this, the optional `**kwargs` argument has been added to the `EnsemblerBase.ensemble` method, meant to take in contextual …
=> Pass original request headers merged with enricher response headers to Pyfunc ensembler

ui/src/services/ensembler/DockerEnsembler.js, ui/src/services/ensembler/PyFuncEnsembler.js, ui/src/services/router/TuringRouter.js
This is a straightforward change to increase the default timeout values for the router components (overall timeout, enricher/router/ensembler timeout), to more realistic values, based on internal feedback.
=> Increase default timeout values for router components

infra/charts/turing/Chart.yaml, infra/charts/turing/templates/service-turing.yaml
Istio [requires](https://istio.io/v1.0/docs/setup/kubernetes/spec-requirements/) service ports to be named in order to work correctly with the routing features. (It is also explained here in detail: [Protocol Selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)). While the current chart works correctly with some basic usage of Istio (i.e. exposing a service via `VirtualService`), it fails to work as expected inside Istio's Service mesh.
This MR adds `http` name to Turing's `Service` and bumps up a patch version of the chart.
=> Satisfy Istio's requirement for named ports

infra/charts/turing/values.yaml, ui/.env, ui/src/config.js, ui/src/jobs/EnsemblingJobsRouter.js, ui/src/jobs/list/ListEnsemblingJobsLandingView.js, ui/src/jobs/list/ListEnsemblingJobsView.js
If batch ensembling is disabled on the Turing API, any attempts by the UI to display the ensembling jobs page will result in an error being shown. This is because the Turing API does not initialise a `EnsemblingJobController` to handle the ensembling job endpoints when batch ensembling is disabled, leading to a `404` response when the UI tries to send a request to the inexistent`/projects/{project_id}/jobs` endpoint when attempting to display the ensembling jobs page.
In order to gracefully avoid such a scenario, this PR introduces an additional landing view for the ensembling jobs page, displaying the usual `ListEnsemblingJobsView` if batch ensembling is enabled or a placeholder message when batch ensembling is disabled. This prevents the UI from sending requests to the inexistent …
=> Add UI handling with batch ensembling disabled

.github/workflows/turing.yaml, ui/package.json, ui/yarn.lock
The MLP logo on Turing UI uses a different version of `mlp-ui` which causes the MLP logo to redirect the user to the landing page of Turing instead of the MLP project landing page. With the changes made in https://github.com/gojek/mlp/pull/52, this PR simply updates the `mlp-ui` version it is using as a dependency to ensure the new changes get incorporated. 
Also made a tiny addition to the GitHub step name that corresponds to the API e2e tests for clarity.
- `ui/package.json` - Dependency updates to `mlp-ui`
- `ui/yarn.lock` - Dependency updates to `mlp-ui`
- `.github/workflows/turing.yaml` - Update to the API e2e test step name for clarity
=> [BUG] Fix NavBar MLP logo to redirect to the MLP dashboard

.github/workflows/trigger-caraml-doc-sync.yml
**What this PR does / why we need it**:
With the migration of `turing` to the CaraML organisation, we are syncing the docs from `turing` automatically to https://github.com/caraml-dev/docs. 
This PR introduces an additional workflow which performs this step, which can be found here: https://github.com/caraml-dev/docs/tree/main/.github/actions/trigger-remote-docs-sync
**Which issue(s) this PR fixes**:
None
=> Add CaraML docs sync workflow

docs/how-to/create-a-router/configure-enricher.md, docs/how-to/create-a-router/configure-ensembler.md, docs/how-to/create-a-router/configure-experiment-engine.md, docs/how-to/create-a-router/configure-routes.md, engines/router/go.mod, engines/router/missionctl/handlers/batch_http_handler.go, engines/router/missionctl/handlers/batch_http_handler_test.go, engines/router/missionctl/handlers/http_handler.go, engines/router/missionctl/handlers/http_handler_test.go, engines/router/missionctl/http/response.go, engines/router/missionctl/internal/testutils/utils.go, engines/router/missionctl/log/resultlog/bigquery_test.go, engines/router/missionctl/log/resultlog/console_test.go, engines/router/missionctl/log/resultlog/resultlog_test.go, sdk/samples/router/create_router_with_pyfunc_ensembler.py
The `turing_req_id` is a unique identifier attached to every response header for each request sent to a Turing Router. However this header is only added just before the response is returned to the user and could instead be sent together as part of requests sent to the other Turing Router components (e.g. enricher, experiments engine, routes, ensembler), allowing users to capitalise on this identifier for other uses (e.g. using the id as a randomisation key).
This PR thus introduces a slight modification to the Turing Router, by adding the `turing_req_id` generated whenever each request is received to all the subsequent request headers that get sent to the other Turing Router components. 
Additionally, this PR replaces the deprecated `ioutil.ReadAll` function with the new `io.ReadAll` …
=> Add turing_req_id in requests made to Turing Router components

engines/router/missionctl/fiberapi/fan_in.go, engines/router/missionctl/fiberapi/fan_in_test.go, engines/router/missionctl/fiberapi/interceptors_test.go, engines/router/missionctl/fiberapi/routing_policies.go, engines/router/missionctl/fiberapi/routing_policies_test.go, engines/router/missionctl/fiberapi/routing_strategy.go, engines/router/missionctl/fiberapi/routing_strategy_test.go, engines/router/missionctl/handlers/http_handler_test.go, engines/router/missionctl/http/response_test.go, engines/router/missionctl/instrumentation/tracing/nop.go, engines/router/missionctl/internal/testutils/response.go, engines/router/missionctl/mission_control.go
Standard Ensemblers allow users to make a Turing Router return a response from one of its routes based on the mapping between routes and experiment treatments. At run time, the treatment returned by the engine will be used to select the corresponding route’s response. A fallback route may also be configured whose results will be used at runtime when the call to the experiment engine fails or if a route mapping for the treatment generated by the experiment engine does not exist.
**To a user, this is the simplest way to set up a final route response given a treatment generated by an experiment engine** - when given a particular treatment, return a specific route response (i.e. if treatment A is received, return the route response from route A).
As of present, Standard Ensemblers are only …
=> Update routing strategy for use with Standard Ensemblers

api/turing/validation/validator.go, api/turing/validation/validator_test.go, ui/src/router/components/form/components/ensembler_config/RouteSelectionPanel.js, ui/src/router/components/form/components/ensembler_config/standard_ensembler/StandardEnsemblerFormGroup.js, ui/src/router/components/form/components/nop_config/NopConfigFormGroup.js, ui/src/router/components/form/steps/EnsemblerStep.js, ui/src/router/components/form/validation/schema.js
**What this PR does / why we need it**:
With the introduction of `Default Traffic Rule` in https://github.com/caraml-dev/turing/pull/232, this PR adds validation to disallow routes that are not associated to any Traffic Rules (a.k.a dangling routes) _**when Traffic rules are specified**_. The motivation is because routes that are not used in any Traffic Rules (if specified), will never be called.
**Validation changes**
`UI`
`API`
`SDK`
=> Disallow Dangling routes with Traffic rules

.github/workflows/cluster-init.yaml, api/e2e/test/testdata/create_router_version.json.tmpl, api/turing/config/config.go, api/turing/config/example.yaml, api/turing/config/testdata/config-1.yaml, api/turing/models/autoscaling_policy.go, infra/cluster-init/init.sh, infra/docker-compose/dev/docker-compose.yml, sdk/e2e/03_create_router_version_test.py, ui/src/router/components/form/components/autoscaling_policy/AutoscalingPolicyPanel.js, ui/src/router/components/form/components/autoscaling_policy/AutoscalingPolicyPanelFlyout.js, ui/src/router/components/form/components/autoscaling_policy/typeOptions.js
This PR is a follow up from the previous ones, to expose autoscaling configurations to the Turing users, and it updates the infra set up to include the HPA along with a few small fixes. Previous PRs:
* https://github.com/caraml-dev/turing/pull/234
* https://github.com/caraml-dev/turing/pull/236
* `.github/workflows/cluster-init.yaml` - Increase the versions of Knative / Knative Istio, to use the same default value used by the cluster init script.
* `api/turing/config/config.go` - Clean up outdated config (also from other test / example files)
* `infra/cluster-init/init.sh`, `infra/docker-compose/dev/docker-compose.yml` - Install the optional [Knative serving extension for HPA](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-optional-serving-extensio …
=> [Infra] Expose user-configurable autoscaling parameters

api/turing/service/router_deployment_service.go, api/turing/service/router_deployment_service_test.go
Autoscaling policy configs were added in https://github.com/caraml-dev/turing/pull/234. When a Pyfunc ensembler is deployed, the autoscaling policy config should be copied to the Docker config of the ensembler, like the other deployment properties. This PR adds this change and a unit test to cover this scenario.
=> Bugfix: Pyfunc ensemblers - copy autoscaling config to docker config

sdk/tests/ensembler_test.py, sdk/turing/ensembler.py
When logging an ensembler, we create / replace the python version conda dependency such that it matches the minor version. Eg: `python=3.7.*`
The comparison function that matched the python dependency from the conda_env dependencies treated each item as a string whereas they could also be objects ([example](https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.log_model)).
This resulted in an error when attempting to create ensemblers with explicit `pip` dependencies. This PR addresses this bug and updates the unit test cases to cover complex dependencies.
=> Bugfix: Handle non-string ensembler dependencies in conda_env

api/db-migrations/000014_autoscaling_policy.down.sql, api/db-migrations/000014_autoscaling_policy.up.sql
Follow up from the previous related bugfix PR: https://github.com/caraml-dev/turing/pull/243
As the docker configs are also present in Pyfunc ensembler configs, the migration scripts need to account for them as well and update the autoscaling policy if the `docker_config` is not NULL (which can happen if the image was never successfully built).
=> Bugfix: Migration for autoscaling configs when using pyfunc ensemblers

api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, api/turing/cluster/knative_service.go, api/turing/cluster/knative_service_test.go, api/turing/cluster/models.go, api/turing/models/autoscaling_policy.go, ui/src/router/components/form/components/autoscaling_policy/AutoscalingPolicyPanelFlyout.js, ui/src/router/components/form/components/autoscaling_policy/typeOptions.js
When the autoscaling metric is set to "memory", Knative expects the target to be supplied in the unit of `Mi` ([ref](https://pkg.go.dev/knative.dev/serving/pkg/apis/autoscaling)). It is common for users to configure the HPA using resource utilization % instead and this is the unit used for the "cpu" metric by Knative as well. Moreover, if `Mi` is used as the unit, the users may need to update the autoscaling target value every time the memory requested is altered.
Thus, this PR changes the handling of the target value set for the memory metric so that the saved config will be treated as `%` and subsequently applied as `Mi`. This will make the configuration consistent for the end users.
* `api/turing/cluster/knative_service.go` - Add method `getAutoscalingTarget` for manipulating the …
=> Accept HPA memory target as %

ui/src/router/components/form/components/ensembler_config/RouteSelectionPanel.js, ui/src/router/components/form/components/router_config/RulesPanel.js, ui/src/router/components/form/validation/schema.js, ui/src/services/ensembler/Ensembler.js
In the run up to the release of a new Turing version, this PR aims to fix several observed bugs in the UI:
- the tooltip from selecting an invalid fallback response route displaying "Route with traffic rules cannot be selected"
- the validation schema for standard ensemblers with custom experiment engines not performing validation correctly during a router update when the `experiment_mappings` field is `undefined` (as saved within the db)
- the '+ Add Rule' button in the create/edit router form being part of an `EuiDroppable` area
https://user-images.githubusercontent.com/36802364/192656894-883ff801-1d03-45e2-8a3e-d43210ac9606.mov
=> Bugfix: Fix UI bugs with standard ensemblers and rules update

ui/src/router/components/form/validation/schema.js, ui/src/services/version/RouterVersion.js
Previously the router diff page does not display the router rules even when changes to them are made. This PR thus introduces a tiny fix that allows the rules configured to be displayed on the diff page.
An additional fix to address https://github.com/caraml-dev/turing/pull/251#discussion_r981861582 has also been made to ensure that only the `route_name_path` or `experiment_mappings` field must be set within the `standard_ensembler` map.
=> Bugfix: Fix diff page to display router rules

ui/src/services/version/RouterVersion.js
With `v1.7.0-rv1` released, several bugs where observed and this PR serves to introduces bug fixes to address them:
- Router version diff page crashing whenever traffic rules are absent 
- Traffic rules (including the default rule) are only added to the pretty print only when they are present
=> Fix v1.7.0-rc1 bugs

ui/src/router/components/configuration/components/pyfunc_config_section/PyFuncConfigViewGroup.js
Incorrect typo of `dockerConfig` which should have been `pyfuncConfig`.
=> Fix Autoscaling config info in the Pyfunc ensembler view

api/go.mod, api/go.sum, api/turing/imagebuilder/ensembler.go
Problem: Users create ensembler names with underscores -> Invalid Kaniko job names -> Invalid K8s jobs -> Router deployments fail
Solution: Add additional API checks to block usage of underscores -> Discovery of bug in existing `go-validator` validation tag to validate ensembler names -> Update `go-validator` -> Done
Pyfunc ensemblers are built as a web service and containerised into a single image upon being deployed as part of a router deployment. This image building process takes place in Kaniko builders run as _jobs_ on a Kubernetes cluster. The Turing API names these jobs automatically, in a way which [incorporates](https://github.com/caraml-dev/turing/blob/main/api/turing/imagebuilder/imagebuilder.go#L133) the user-registered name of the ensemblers to be built:
```go
kanikoJobName …
```
=> Bugfix: Fix RFC-1123 hostname string validation for ensembler names

infra/cluster-init/init.sh, ui/src/router/components/form/components/ensembler_config/standard_ensembler/StandardEnsemblerFormGroup.js, ui/src/router/components/form/steps/EnsemblerStep.js, ui/src/router/components/form/steps/ExperimentStep.js
This PR addresses 2 main bugs that have been found with the UI:
1. Currently when editing a router, if a user changes from a custom experiment engine to a standard engine, both of which use Standard Ensemblers, the UI crashes because it supposedly is unable to locate the list of experiments configured for the standard experiment engine.
This in reality, happens only momentarily when an [effect](https://github.com/caraml-dev/turing/blob/345e9b001adaa7da95b0f99757ce15672711c1f0/ui/src/router/components/form/steps/ExperimentStep.js#L27) is triggered to reset the experiment config when a different experiment engine is selected. During this short span of time, the `experiments` field within the experiment config is undefined and hence the UI crashes. Hence, a fallback array is passed to the …
=> Bugfix: Fix UI crashes when changing between experiment engines

ui/src/AppRoutes.js
This PR is a follow up from https://github.com/caraml-dev/turing/pull/265, which missed a `/*` pattern in the experiments landing page, to allow matching the nested routes exposed by the remote component correctly.
=> Bugfix: Fix experiments landing page path

ui/src/Home.js, ui/src/PrivateLayout.js
This is a follow up from the previous PRs and addresses some regressions introduced by the first:
* https://github.com/caraml-dev/turing/pull/265
* https://github.com/caraml-dev/turing/pull/271
Fixes the following issues:
* `ui/src/PrivateLayout.js` - Header's homepage should be empty (default "/") so that in the multi-app deployment, clicking the header logo can take us to the MLP landing page.
* `ui/src/Home.js` - Navigating to `/turing` in the deployed app should automatically redirect to the index page for Turing (list routers) if the current project is chosen.
=> Bugfix: Navigation with react-router-dom

api/Makefile, api/README.md, engines/experiment/examples/plugins/hardcoded/Makefile, engines/router/Makefile
Fix incorrect `make build-local-router-image` where `IMAGE_TAG` is empty when executing the following:
```
docker push $(IMAGE_TAG)
```
Also, better naming of Make command.
=> Fix and rename make commands for local E2E

engines/router/missionctl/server/application.go
Since we use cmux to multiplex connection to grpc or http, there is match rule that will redirect request to correct server. Current match rule that we use won't work for some of grpc client due to some of grpc client will blocks until it receives `SETTINGS` frame from the server. In this PR we change the match rule so it can handle all the grpc client
ref: [https://github.com/soheilhy/cmux#limitations](https://github.com/soheilhy/cmux#limitations)
=> Fix some of grpc client that get stuck when access grpc server

api/turing/models/router.go, api/turing/models/router_test.go, api/turing/service/router_deployment_service.go, api/turing/service/router_deployment_service_test.go
After changing the implementation  in https://github.com/caraml-dev/turing/pull/255, `api/turing/service/router_deployment_service.go` , the endpoints are persisted with `/v1/predict` in the db. This is a problem as Turing can support more than one specific endpoint (/v1/batch_predict)
HTTP endpoint are expected to start with `http`, GRPC endpoint to start with host and end with port appended.
1. Reverting `api/turing/service/router_deployment_service.go` to not prepend /v1/predict
2. Add custom marshalling in `models/router.go` to append `/v1/predict`, API calls will then get `/v1/predict`
3. Added unit test `models/router.go` to test http/grpc/nil endpoint
Tested local, one UPI Router (id 1) and HTTP Router (id 2)
API calls, `v1/predict` appended to HTTP endpoint only
=> bugfix router endpoint in db

api/turing/cluster/servicebuilder/fluentd.go, api/turing/cluster/servicebuilder/fluentd_test.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/testdata/config-1.yaml, engines/router/compose/fluentd.yaml, scripts/fluentd-bigquery/.env.template, scripts/fluentd-bigquery/Dockerfile, scripts/fluentd-bigquery/fluent.conf
This PR adds configuration to support worker counts in Fluentd. With more traffic, Fluentd tends to be more CPU bound. In this case, we should consider using [multi-worker](https://github.com/deployment/multi-process-workers) feature.
=> Support configurable worker count for Fluentd

api/turing/cluster/servicebuilder/router.go, api/turing/testdata/cluster/servicebuilder/router_configmap_traffic_splitting.yml
Updating the Fiber config builder to use the user-defined traffic rule name as opposed to `traffic-split-X`. This will help propagate the user-defined names to the custom metric `traffic_rule` label introduced in https://github.com/caraml-dev/turing/pull/280.
=> Update traffic rule names in fiber config

.github/workflows/sdk.yaml
Due to an incorrect distribution of the Turing SDK being previously released as `v0.7.0`, as well as vertagen being unable to determine the correct version tag of the next release of the Turing SDK, this PR introduces an env var to the Turing SDK CD pipeline to manually overwrite the version number of the release as `v0.7.1`. 
- `.github/workflows/sdk.yaml` - Addition of the `OVERWRITE_VERSION` env var to the `make build` command of the CD pipeline
=> Add env var to manually release SDK as v0.7.1

.github/workflows/sdk.yaml
In PR #294, a temporary change was made to allow the SDK to be released with a version that's manually specified. This PR reverts the changes made in that PR.
- `.github/workflows/sdk.yaml` - Removal of the env var `OVERWRITE_VERSION`
=> Remove env var to release SDK manually

.github/workflows/pyfunc-ensembler-job.yaml, .github/workflows/pyfunc-ensembler-service.yaml, .github/workflows/sdk.yaml, engines/pyfunc-ensembler-job/Dockerfile, engines/pyfunc-ensembler-job/env-3.10.yaml, engines/pyfunc-ensembler-job/env-3.7.yaml, engines/pyfunc-ensembler-job/env-3.8.yaml, engines/pyfunc-ensembler-job/env-3.9.yaml, engines/pyfunc-ensembler-job/requirements.txt, engines/pyfunc-ensembler-job/setup.py, engines/pyfunc-ensembler-service/env-3.10.yaml, engines/pyfunc-ensembler-service/setup.py, sdk/requirements.txt, sdk/samples/router/general.py, sdk/setup.py, sdk/tests/fixtures/mlflow.py
With the introduction of Python 3.10 for over a year, it is high time to introduce support for this version for the Turing SDK. This PR introduces changes needed to accommodate Python 3.10 in the SDK as well as all components that depend on it. 
Additionally, this PR modifies the existing CI/CD workflows that cover this new Python version that Turing will be supporting.
=> Add Python 3.10 support

api/go.mod, api/go.sum, engines/router/go.mod, engines/router/go.sum
In fiber 2.0, when Traffic Rules are used with `Selective` routing strategy in standard ensembler setup. Underlying, the router are composed of two nested `lazy router`. With the default `Exhaustive` routing strategy, it is composed of a parent `lazy router` (which is used for traffic splitting) and child `eager router` (to call all routers in parallel).
Fiber 2.1-rc1 fixes the above problem with route request duration metric but introduce another bug to route component metric To explain in context
**Fiber 2.0**
Step 1 Parent layer - lazy router (for both routing strategy)
1. Lazy router calls `TrafficSplittingStrategy` and obtain the traffic rule labels
2. Invoke child common with traffic labels added to context
Step 2a Second layer - eager router (exhaustive strategy)
1. Calls all …
=> revert fiber to 2.0

api/turing/cluster/job.go, api/turing/cluster/job_test.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/imagebuilder/imagebuilder.go
This PR introduces two additional configuration to the `ImageBuildingConfig`:
1. `NodeSelector` which allows operators of the Turing API server to set labels such that the image building jobs (and the pods they spin up) only scheduled on nodes with those labels and,
2. `TolerationName` which allows operators of the Turing API server to set a toleration name such that image building jobs will be deployed with the specified toleration name, allowing them to be scheduled on nodes with the matching taint.
=> Add NodeSelector and TolerationName to ImageBuildingConfig

engines/router/missionctl/server/upi/logutils.go, engines/router/missionctl/server/upi/logutils_test.go
This PR add marshal option to the protojson marshaller to use proto name (separate words by underscore instead of camelCase) and a test for logging that will assert the format. Also to address a previous [PR](https://github.com/caraml-dev/turing/pull/301/files)  `engines/router/missionctl/server/upi/logutils.go` whereby the request was logged as response without noticing.
Using the default marshaller, the proto keys are camelcase which is not consistent
=> fix json formatting of logs proto

sdk/tests/fixtures/mlflow.py, sdk/turing/session.py
When authentication is enabled and the Google Auth credentials are loaded, the SDK is now made to refresh the credentials, to get around the following issue which affects Compute Engine workload identity: https://github.com/googleapis/google-auth-library-python/issues/1211
Related PR on Merlin: https://github.com/gojek/merlin/pull/339
=> Refresh credentials in SDK on load

api/e2e/test/config/config.go, api/go.mod, api/turing/validation/validator.go, api/turing/validation/validator_test.go
As of present, Turing Routers created/updated with an `nop` experiment engine and a standard ensembler configured are not blocked by the Turing API server. Such router configurations are invalid because standard ensemblers are not meant to be utilised without an experiment engine. Hence, an appropriate error needs to be thrown whenever a user tries to create/edit routers with such a configuration. 
While the UI currently prevents such a scenario from occurring due to how it manages the router creation/edit workflow, an additional API validation check needs to be introduced so as to prevent such a scenario from occurring if users were to send requests to the API directly or via the SDK. This PR introduces such a check that throws an error if the aforementioned invalid configuration is used …
=> Bugfix: Throw error when a router is created with an nop exp engine and a standard ensembler

api/turing/cluster/servicebuilder/router.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/testdata/config-2.yaml, api/turing/testdata/cluster/servicebuilder/router_configmap_exp_engine.yml, api/turing/testdata/cluster/servicebuilder/router_version_success_experiment_engine.json, engines/router/missionctl/experiment/experiment.go, engines/router/missionctl/experiment/experiment_test.go, engines/router/missionctl/fiberapi/fan_in_test.go, engines/router/missionctl/fiberapi/routing_policies.go, engines/router/missionctl/fiberapi/routing_strategy_test.go, infra/charts/turing/templates/_helpers.tpl, infra/e2e/turing.values.yaml
Given the recent changes to [XP](https://github.com/caraml-dev/xp)'s experiment engine plugin to refactor its entire Treatment Service logic into a plugin, it has been observed that there would be an increased likelihood of the plugin failing due to its increased complexity. While this only affects XP's plugin, it has been decided that an experiment engine plugin failure, in general, should be handled differently by the Turing Router.
As of present, a Turing Router merely receives an error message when calling the `GetTreatmentForRequest` method of an experiment engine that has crashed, which conflates with regular error messages returned by the experiment engine plugin even when it is running normally. Hence, a separate way needs to be introduced to determine the health of the plugin, …
=> Add plugin monitoring by pinging it async

api/Dockerfile
* This PR adds `gke-gcloud-auth-plugin` to turing-api can access gke clusters without having to provide static credentials (ie client cert key, private key)
* This PR can be merged without affecting any existing logic
Reason:
* GKE clusters now support [authentication via plugin](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke)
* `gke-gcloud-auth-plugin` is a go binary. Source code can be found [here](https://github.com/kubernetes/cloud-provider-gcp/tree/master/cmd/gke-gcloud-auth-plugin)
* There are 3 ways to install the plugin:
1) via gcloud cli: `gcloud components install gke-gcloud-auth-plugin --quiet`
2) via `go install <package>`
* Howver, `go install <plugin>` returns this error
```sh
➜ go install …
```
=> Add gke-gcloud-auth-plugin to dockerfile

api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/testdata/config-1.yaml
* This PR fixes a marshelling issue when reading in `ClusterConfig.EnsemblingServiceK8sConfig`, which results in some `k8sConfig.Cluster` fields not being read.
* This error was not detected in the e2e tests, as none of the routers created in e2e tests use the pyfunc ensemblers
`config.Load()` has been modified to further unmarshall `EnsemblingServiceK8sConfig` if it is present, using `"sigs.k8s.io/yaml"`.
=> Fix marshalling issue in config.Load()

engines/router/Dockerfile
This PR introduces the `tzdata` installation within the Turing Router image so as to allow it and other experiment engine plugins to utilise timezone related tools.
=> Add tzdata dependency to Turing Router

infra/cluster-init/init.sh
Follow up from https://github.com/caraml-dev/turing/pull/305
- Fix typo in default Knative version in init cluster script's help string
- Update Knative Isio component version to `1.7.1` in init cluster script.
=> Fix typo: Init cluster knative version help string

sdk/requirements.txt, sdk/turing/session.py
As of present, authentication is performed by the Merlin and Turing SDKs using Google OAuth 2.0 access tokens (generated after authentication with Google's OAuth server) that are added to the headers of requests sent to the Turing API server. These tokens are then used by an internal proxy which will validate the access token and then retrieve the user profile information from the Google API. 
However, in keeping with the move of the Google Identity Services client library from OAuth 2.0 access tokens to Google OpenID Connect (OIDC) identity tokens, we are similarly replacing the use of the former for the latter. These tokens generated would similarly be added to the headers of requests sent to the Turing API server to be validated internally. 
A utils module `caraml_auth` in the package …
=> Change authentication method to use OIDC identity tokens

sdk/requirements.txt
The new version of the Turing SDK which incorporates changes to authenticate the user with OpenID Connect tokens did not manage to be pushed successfully to the PyPI repository because it was using a Git dependency on `caraml-auth-google`, which Git dependencies are not allowed by PyPI. 
Since then, `caraml-auth-google` has been finally released directly to PyPI, paving way for the Turing SDK to update its dependency on it to utilise the released version directly. This PR updates that version directly in the `requirements.txt` file.
=> Update caraml-auth-google version

api/turing/cluster/knative_service.go, api/turing/cluster/knative_service_test.go, api/turing/cluster/servicebuilder/router.go, api/turing/cluster/servicebuilder/router_test.go, api/turing/cluster/servicebuilder/service_builder.go, api/turing/cluster/servicebuilder/service_builder_test.go, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/testdata/config-1.yaml, api/turing/service/router_deployment_service.go, infra/cluster-init/knative-configmaps/config-features.yaml
[Topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) allow the distribution of pods across various topology domains to be controlled at a finer level than with pod affinities/anti-affinities. As the current implementation of the Turing API server does not allow Knative services (Turing Routers, enrichers, pyfunc/docker ensemblers) to be deployed with topology spread constraints, this PR introduces changes to allow the Turing API server operator to specify topology spread constraints in the Turing API configuration which will get propagated to all Knative services deployed. 
In addition, in order to encourage pods of the same Knative service deployed by the Turing API server to be scheduled on a largest variety of nodes …
=> Add topology spread constraints to deployments

api/e2e/test/config/config.go, api/e2e/test/router_e2e_test.go, api/turing/api/alerts_api.go, api/turing/api/ensemblers_api.go, api/turing/api/ensembling_job_api.go, api/turing/api/experiments_api.go, api/turing/api/router_versions_api.go, api/turing/api/routers_api.go, api/turing/cluster/servicebuilder/router.go, api/turing/cluster/servicebuilder/router_test.go, api/turing/cluster/servicebuilder/service_builder.go, api/turing/cluster/servicebuilder/service_builder_test.go, api/turing/service/router_deployment_service.go, api/turing/service/router_deployment_service_test.go, api/turing/service/router_version_service.go, sdk/e2e/01_create_router_test.py, sdk/e2e/06_deploy_valid_config_test.py
After the Gorm library has been updated to v2 in #261, there is a bug discovered in how we're using the Gorm methods to save router versions to the DB whereby nested fields (such as the ensembler configs) do not get updated in their respective tables. This has caused deployed pyfunc ensemblers to not have their corresponding docker configs updated in the `ensembler_configs` table. Since these are left as `NULL`, what then happens downstream is that the cluster controller fails to build KnativeService objects that correspond to the deployed ensembler instances, causing it to be unable to deploy ensemblers that have been deployed (either as part of a router update operation or an undeployment operation).
~~This PR introduces a config to the Gorm DB layer which adds a new field …
=> Bugfix: Fix pyfunc ensembler undeployment bug

api/config-dev.yaml, api/turing/cluster/job.go, api/turing/cluster/job_test.go, api/turing/config/config.go, api/turing/config/example.yaml, api/turing/imagebuilder/imagebuilder.go, infra/charts/turing/values.yaml
The image-building jobs in Turing and Merlin are timing out. After some investigation, we found that one of the root causes is the node pool got scaled down resulting in the image building pods to be rescheduled. This PR adds "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" to avoid the pod get killed and rescheduled.
Related Merlin's PR: https://github.com/caraml-dev/merlin/pull/380
=> Add safe-to-evict annotation to image builder job

ui/src/PrivateLayout.js
With the Applications v2 API introduced in https://github.com/caraml-dev/mlp/pull/72, the homepage URL is supposed to be read from the `homepage` property of the current app stored in the applications context, as opposed to `.href`. The MLP PR was integrated to Turing through the UI library bump done in https://github.com/caraml-dev/turing/pull/333. This PR updates the nav URL accordingly.
=> Bugfix: Update navbar project URL

api/go.mod, api/go.sum
This PR updates the version of MLP uses in order to incorporate this change [here](https://github.com/caraml-dev/mlp/pull/84), which allows Turing to use workload identity-enabled service account to authenticate all its outgoing resources.
=> Update mlp dependency

sdk/tests/router/config/router_config_test.py, sdk/turing/router/config/router_config.py
Short: Remove validation in SDK for UPI Router that was missed earlier on.
When UPI Logger was [first introduced](https://github.com/caraml-dev/turing/pull/319/files#diff-49fa6d9d67eac9ae9ac62b762e4db2c2b72de2d407f4a5aa1930e94a0f187a97), it was never intended to work with BQ/Kafka ResultLogger. 
Subsequently, BQ/Kafka logger are enabled for UPI Router in this [PR](https://github.com/caraml-dev/turing/pull/323/files#diff-2bc7d30f97d4ecb41bd4e1ac0a1727086edf6557f30f409991db83e1d7278bcd) 
using `TuringResultLog` instead of `RouterLog` and the validation for these were removed for the API Server but not SDK.
This PR removes the SDK validations that should had been removing with the previous PR.
=> Bugfix: remove validation for resultlogger of upi router in sdk

api/go.mod, api/go.sum, api/turing/config/config.go, api/turing/config/config_test.go, api/turing/config/example.yaml, api/turing/config/testdata/config-1.yaml, api/turing/middleware/authorization.go, api/turing/server/application.go
This PR largely replicates the changes for the API in https://github.com/caraml-dev/mlp/pull/87, to have the option of caching authz responses. As a part of this implementation, the API dependency on MLP has been upgraded.
=> feat: Add authz caching config

api/turing/config/config.go, api/turing/imagebuilder/imagebuilder.go, api/turing/imagebuilder/imagebuilder_test.go
As of present, when the Turing API server triggers an image building job as part of launching a batch ensembling job/service, it checks for the presence of an existing image building job in the cluster with the same name. The status of the image building job found (if it is found), corresponds to a variety of situations:
- Found; running -> an existing image building job is already taking place and still running -> wait for the job to complete
- Found; failed -> an existing image building job has failed -> delete the old job -> begin a new one
- Not found -> begin a new one
In particular, we're interested in the **_second_** scenario, where there a new job is triggered right after the deletion of the old (failed) run (see [this](https://github.com/caraml-dev/turing/blob/33388a254167964c12d …
=> Bugfix: Add image building job deletion delay

api/turing/middleware/authorization.go
This PR corrects the path manipulation when checking for authorization, to trim the path prefix, which was accidentally removed in: https://github.com/caraml-dev/turing/pull/344
=> fix: Trim path prefix when checking for authorization

api/go.mod, api/go.sum, engines/experiment/examples/plugins/hardcoded/go.mod, engines/experiment/examples/plugins/hardcoded/go.sum, engines/experiment/go.mod, engines/experiment/go.sum, engines/router/go.mod, engines/router/go.sum, engines/router/missionctl/log/resultlog/upi_result_log_test.go, engines/router/missionctl/server/upi/interceptors/recoverer.go, engines/router/missionctl/server/upi/interceptors/recoverer_test.go, engines/router/missionctl/server/upi/server.go
Turing router crash when trying to convert invalid UPI request. The root cause is due to bug in the UPI utility function to convert UPI table in struct. Following are the modifications:
* Bump version of UPI libarary
* Add panic recovery interceptors
=> Fix crash due to mismatch number of columns and values in a row

sdk/tests/router/config/router_ensembler_config_test.py, sdk/turing/router/config/router_ensembler_config.py
This PR adds a small fix in `sdk/turing/router/config/router_ensembler_config.py`, which was preventing experiment mappings in the Standard Ensembler Config from being saved correctly, in the result of a get/list router call.
Added unit tests to test the initialization of `RouterEnsemblerConfig` with different types of configs, and that the resulting structure has the all the relevant data stored.
=> fix: Missing experiment mappings in standard ensembler config

ui/src/ensembler/list/ListEnsemblersTable.js, ui/src/jobs/list/ListEnsemblingJobsTable.js
This PR is a follow up regarding some issue from the #329 :
1. Different table alignment from turing and merlin
2. Hide Terminate/Delete Button when ensembling job is on `terminating` state
=> fix some styling on the deletion feature

ui/src/ensembler/components/modal/DeleteEnsemblerModal.js, ui/src/ensembler/components/table/ListEnsemblingJobsForEnsemblerTable.js, ui/src/ensembler/components/table/ListRouterVersionsForEnsemblerTable.js, ui/src/jobs/components/modal/DeleteJobModal.js, ui/src/jobs/list/ListEnsemblingJobsTable.js
Similar to PR #348 which introduced some UI fixes to the ensembler deletion workflow (which itself had been introduced in PR #329), this PR acts as a follow up to implement some additional minor fixes to the UI for the bugs below:
- when deleting multiple ensemblers in a row, the confirmation text box in the pop-up gets pre-filled with the ensembler name from the previous ensembler that had been deleted
- when opening and closing the deletion pop-up multiple times in a row (without actually deleting the ensembler), the information shown in the pop-up is not consistent (see the video at the bottom of this description for an illustration).
Besides these bug fixes, some other non-bug related improvements have been introduced:
- some minor changes to the formatting of the pop messages to …
=> Fix ensembler deletion UI bugs

api/turing/service/router_deployment_service.go, api/turing/service/router_deployment_service_test.go
PDB support for router components was introduced in https://github.com/caraml-dev/turing/pull/346. This PR fixes some bugs / corner cases:
* For ensembler, PDB should only be created for Docker / Pyfunc types (as Standard ensembler is embedded in the router deployment)
* Do not create PDB if the min replica is too low, which can prevent node drain. See related Merlin PR for more details: https://github.com/caraml-dev/merlin/pull/436
=> fix: Add precautionary logic for PDB

ui/src/jobs/components/modal/DeleteJobModal.js, ui/src/jobs/list/ListEnsemblingJobsTable.js, ui/src/services/job/JobStatus.js
This context inverts the logic of the `isActiveJobStatus` helper function used in the UI, since its name doesn't really represent what it actually does (it actually does the inverse 👀)
=> fix: Invert logic of isActiveJobStatus helper function

api/turing/api/ensemblers_api.go, api/turing/api/ensemblers_api_test.go, ui/src/ensembler/components/modal/DeleteEnsemblerModal.js
When an ensembler gets deleted, checks are performed to see if there are any associated ensembling jobs that use it. However, these checks are unnecessary and should not be performed if batch ensembling has been deactivated in the first place. Doing so triggers bugs and other errors because the ensembling job service or controllers wouldn't be initialised during start up of the Turing API server. 
This PR thus introduces some additional checks to ensure that these checks are skipped if batch ensembling is turned off, so as to prevent such bugs:
- on the UI level: prevent the ensembler deletion pop up from sending any requests to the Turing API server to retrieve a list of related ensembling jobs if batch ensembling is turned off
- on the API level: prevent the delete ensembler handler …
=> fix: Prevent calls to ensembling job service/controllers if batch ensembling is deactivated

api/turing/cluster/job.go, api/turing/cluster/job_test.go, api/turing/config/config.go, api/turing/imagebuilder/imagebuilder.go
Similar to how https://github.com/caraml-dev/merlin/pull/352 introduced a Kubernetes service account to be used for Kaniko jobs orchestrated by Merlin, this PR similarly introduces a similar change for Turing in its API server so that it is able to pass a configured Kaniko service account name to all the Kaniko jobs it orchestrates.
Note that not a lot of changes (if any) were made to the unit tests, despite the addition of a new service account (name) field, unlike in the Merlin repo. This is normal since Merlin is currently testing the image job creation workflows much more [extensively](https://github.com/caraml-dev/merlin/blob/da431b86a091b7966a65858f5961b432e8eeade6/api/pkg/imagebuilder/imagebuilder_test.go#L1294) in its unit tests, which isn't the case in Turing (we are only …
=> Add kaniko service account to image builder configs

docs/SUMMARY.md, docs/how-to/delete-an-ensembler/README.md, docs/how-to/delete-an-ensembler/delete-an-ensembler-active.md, docs/how-to/delete-an-ensembler/delete-an-ensembler-inactive.md, docs/how-to/delete-an-ensembler/delete-an-ensembler.md
This tiny-PR rewords certain parts of the ensembler deletion docs that were added in #329 to make them more consistent or to remove certain sentences that are repeated in various sections. There are also some changes to the sentences to make them simpler and more succinct.
- `docs/how-to/delete-an-ensembler/*` - Rewording of some parts of the documentation
=> docs: Reword certain parts of the ensembler deletion docs

engines/pyfunc-ensembler-job/app.Dockerfile, engines/pyfunc-ensembler-service/app.Dockerfile
With the changes in PR #357, there is a need to make additional changes to the Dockerfiles of the Kaniko image building templates - instead of authenticating immediately with `GOOGLE_APPLICATION_CREDENTIALS`, we now first check if that env var is defined, if so we will authenticate with the credentials stored in the file path pointed to by that env var; otherwise, the `gcloud auth activate-service-account` will not be run in the Dockerfile. In the second scenario, the Google service account credentials are expected to be passed to the Kaniko image building jobs via a mounted Kubernetes service account.
A similar change has been implemented in Merlin: https://github.com/caraml-dev/merlin/pull/352/files#diff-931d889c572814da3e253178b316471ac9878c45bf0497dd1792b5442eab359cR24
=> fix: Add check before activating service accounts in Kaniko build jobs

sdk/requirements.txt
This PR is a fix to PR #343 which updated the `caraml-auth-google` package to use an older version of `urlllib3`. Previously, the `caraml-auth-google` package had an incorrect version of `urllib3` pinned; this PR thus updates the version of `caraml-auth-google` from `0.0.0.post6` to `0.0.0.post7`.
=> fix: Bump up caraml auth google

engines/pyfunc-ensembler-job/Dockerfile, engines/pyfunc-ensembler-service/Dockerfile
Anaconda repo is no longer free for use, for companies with over 200 employees: https://community.anaconda.cloud/t/is-conda-cli-free-for-use/14303
This PR replaces `continuumio/miniconda3` used as the Pyfunc ensembler service base image with an image that uses [Miniforge](https://github.com/conda-forge/miniforge). With Miniforge:
> [conda-forge](https://conda-forge.org/) set as the default (and only) channel
Additionally, the Miniforge conda version in the batch ensembler base image is updated to the latest as well.
=> Use miniforge conda as Pyfunc ensembler service base image

README.md, engines/pyfunc-ensembler-service/Dockerfile, engines/pyfunc-ensembler-service/app.Dockerfile, infra/charts/turing/values.yaml
This PR upgrades the Kaniko image version used in the Turing infra chart.
With this Kaniko version, the Pyfunc ensembler service image builds require a lot more memory and often get OOMKilled (based on internal tests). Thus, to get around this, the multi-stage build is removed from the `Dockerfile` (which is the same approach as Merlin's Pyfunc models - [ref](https://github.com/caraml-dev/merlin/blob/v0.33.0/python/pyfunc-server/docker/Dockerfile)) to save build time and resources.
However, removing the multi-stage build does result in a larger built image size (about 500MB larger). Optimizing the image building process will be taken up separately.
=> Remove multi-stage build from Pyfunc ensembler service

api/turing/api/ensemblers_api.go, api/turing/api/ensemblers_api_test.go
The delete ensembler API endpoint currently returns an `int` (representing the id of the deleted ensembler) as part of a 200 response if the deletion occurs successfully. This is inconsistent with the specification in the Turing API server's OpenAPI specs which specifies a struct with the schema `{"id": [ensembler id]}` (this itself is consistent with the delete router API endpoint responses). See https://github.com/caraml-dev/turing/blob/main/api/api/specs/ensemblers.yaml#L147 and https://github.com/caraml-dev/turing/blob/main/api/api/specs/common.yaml#L14 for the exact schema definitions.
As such, using the Turing SDK to delete ensemblers would throw errors as the autogenerated OpenAPI classes would expect a struct in the response body instead of an `int`. This PR thus fixes the …
=> fix: Change delete ensembler api response from int to struct

.github/workflows/pyfunc-ensembler-job.yaml, .github/workflows/pyfunc-ensembler-service.yaml, engines/pyfunc-ensembler-job/Dockerfile, engines/pyfunc-ensembler-job/env-3.7.yaml, engines/pyfunc-ensembler-job/requirements.txt, engines/pyfunc-ensembler-job/setup.py, engines/pyfunc-ensembler-service/env-3.7.yaml, engines/pyfunc-ensembler-service/requirements.txt, engines/pyfunc-ensembler-service/setup.py, sdk/samples/quickstart/quick_start.py, sdk/tests/ensembler_test.py
This MR is the continuation of https://github.com/caraml-dev/turing/pull/362 and drops Python 3.7 support also from the Pyfunc servers for real-time and batch ensemblers.
Docs and examples are also updated to replace Python 3.7 with a higher version.
In addition, the base image for the batch ensembler job is updated to `apache/spark-py:v3.1.3` as the Google spark operator image has been recalled due to vulnerabilities. Ref: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1862
=> Remove support for Python 3.7

docs/how-to/create-a-router/configure-ensembler.md, engines/pyfunc-ensembler-job/requirements.txt, sdk/requirements.dev.txt, sdk/requirements.txt
This PR upgrades the `mlflow` client dependency on the SDK (and therefore the Pyfunc servers) to `mlflow>=1.26.1,<2.0.0`. Accordingly, the `protobuf` dependency range is updated as well.
Related MRs in Merlin:
* https://github.com/caraml-dev/merlin/pull/465
* https://github.com/caraml-dev/merlin/pull/485
* https://github.com/caraml-dev/merlin/pull/486
* https://github.com/caraml-dev/merlin/pull/487
=> Upgrade MLflow client

api/turing/imagebuilder/ensembler.go, api/turing/imagebuilder/imagebuilder.go, api/turing/imagebuilder/imagebuilder_test.go
This fix/enhancement revises the image naming convention for both ensembler service and ensembler job images built by the image builder:
```
{dockerRegistry}/{projectName}-{ensemblerName}-{runID}-service:{ensemblerID}
```
or
```
{dockerRegistry}/{projectName}-{ensemblerName}-{runID}-job:{ensemblerID}
```
```
{dockerRegistry}/{projectName}/ensembler-services/{ensemblerName}:{runID}
```
or 
```
{dockerRegistry}/{projectName}/ensembler-jobs/{ensemblerName}:{runID}
```
By removing the `runID` from the image name, we now allow all images built for the same ensembler to be stored within the same image repository as opposed to storing them in separate repositories. Furthermore, since all built images of the same ensembler will now be stored in the same repository, we now tag them with their …
=> fix(image-builder):Refactor ensembler image naming convention

ui/src/router/components/form/components/ResourcesPanel.js
Similar to https://github.com/caraml-dev/merlin/pull/546 whereby the min-max replica slider bar has been slightly modified by removing the ticks to better accommodate larger ranges (e.g. 100 replicas), this PR makes similar changes to the Turing UI in order to keep the design of the resource request components similar in both Turing and Merlin.
Notice how the min and max values are now displayed as labels at the ends of the slider bar.
- `ui/src/router/components/form/components/ResourcesPanel.js` - Removal of ticks and addition of min-max labels
=> feat(ui): Remove ticks and display min-max labels in EuiDualRange slider

api/turing/batch/ensembling/runner.go, api/turing/cluster/labeller/labeller.go, api/turing/cluster/labeller/labeller_test.go, api/turing/cluster/servicebuilder/service_builder.go, api/turing/cluster/servicebuilder/service_builder_test.go, api/turing/service/router_deployment_service.go
* Currently, MLP Project `labels` are not applied to resources (routers, enrichers, image creation jobs, etc) created by Turing
* This MR modifies the labeller package to include the project level labels (from mlp project object) in addition to the standard (orchestrator, stream, team, etc) labels added
=> feat: Include mlp project labels in created resources labels

api/turing/imagebuilder/imagebuilder.go
Following up on the changes to edit the naming convention of docker images built by the Turing API server in PR #368, this PR introduces a tiny fix to a part of the image building process that checks for the existence of a docker image with the same tag.
Previously the tag was left as the ensembler id, which is incorrectly, given the changes proposed in PR #368. This PR corrects the image tag used for the check mentioned above to the ensembler run id. Here's a recap of how the changes should look like:
```
{dockerRegistry}/{projectName}-{ensemblerName}-{runID}-service:{ensemblerID}
```
or
```
{dockerRegistry}/{projectName}-{ensemblerName}-{runID}-job:{ensemblerID}
```
```
{dockerRegistry}/{projectName}/ensembler-services/{ensemblerName}:{runID}
```
or 
``` …
```
=> fix(api): Fix incorrect tag name used to check for the existence of built docker images

engines/experiment/pkg/request/request.go, engines/experiment/pkg/request/request_test.go
Update to the `engines/experiment/pkg/request/request.go` to support object and array type.
The underlying method does support object and array by presumingly older requirements then, these type are not supported. However due to evolving experiment segments that involves array and dictionary, these would required to be updated
=> feat: support array in experiment engine json

engines/pyfunc-ensembler-service/requirements.dev.txt, sdk/requirements.dev.txt, sdk/tests/router/config/router_version_test.py, sdk/turing/router/config/router_config.py
When using the UI to update an existing router that has an experiment engine configured, the passkey field is rendered as a dummy [text](https://github.com/caraml-dev/turing/blob/84339fa1c440ee923c0137eea073a1068479a58f/ui/src/services/experiment_engine/ExperimentEngine.js#L24) `"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"` even though in reality, the UI receives the value of the encrypted passkey through a GET request to the API server. This is done so as to not reveal any passkey, encrypted or not. If this dummy value is not overwritten in the update, the passkey of the current router version (if it exists) is automatically reused in the new router version. This happens because the passkey (encrypted by the API server) that's in the existing router version gets replaced by the UI with an …
=> fix(sdk): Remove exp engine passkey when retrieving routers from the API server

api/turing/api/ensembler_images_api.go, api/turing/imagebuilder/imagebuilder.go
The previous JobState is `int` and uses `iota` together in the same const block with other values. This lead to JobState is starting from 3 instead of 0.
Using `int` for `JobState` requires mapping implementation in SDK.
This PR refactors JobState from `int` to `string` so that it easier to parse by SDK and to make it consistent with Merlin implementation (https://github.com/caraml-dev/merlin/blob/main/api/models/version_image.go#L15-L20).
=> fix(api): Refactor JobState to string

api/turing/cluster/knative_service.go, api/turing/cluster/knative_service_test.go, ui/src/router/components/form/components/autoscaling_policy/AutoscalingPolicyPanel.js, ui/src/router/components/form/validation/schema.js, ui/src/services/version/RouterVersion.js
This is a follow up on PR #378, which introduces additional fixes and some minor refactoring to make the UI and API server behaviour consistent with that of Merlin's, especially with regards to the handling of autoscaling target values.
In short, this PR does the following:
1. On the UI, removal of all integer parsing/verification of all autoscaling targets (this will now be handled in a more sophisticated manner in the API server; see below for more information)
2. On the API server, introduction of additional handling to parse CPU and RPS autoscaling targets to integers
=> fix(api,ui): Fix autoscaling target parsing

ui/src/services/ensembler/Ensembler.js, ui/src/services/router/TuringRouter.js
Certain fields in a router's ensembler config need to be removed manually before being stringified into a JSON object that will be sent to the Turing API server as the payload in various HTTP calls (e.g. update router, create new router version, etc.):
- `ensembler` (the entire ensembler config)
- `ensembler.standard_config.fallback_response_route_id` 
- `ensembler.docker_config`
- `ensembler.docker_config.resource_request.cpu_limit` / `ensembler.pyfunc_config.resource_request.cpu_limit` 
This was previously handled in the `toJson` method of the a `TuringRouter` object which gets called when `JSON.stringify` gets called on the `TuringRouter` object. However, in reality, this **did not remove any of the ensembler configs** listed above.
When `JSON.stringify` gets called on an object …
=> fix(ui): Fix incorrect steps to remove ensembler fields 

ui/src/components/pod_logs_viewer/PodLogsViewer.js, ui/src/config.js, ui/src/router/details/RouterDetailsView.js, ui/src/router/details/logs/RouterLogsView.js, ui/src/utils/createStackdriverUrl.js
Similar to how the Merlin logs tab displays links to stored logs on stackdriver (Google Cloud Logging) in addition to live logs, this PR adds a panel to the router logs tab to display links to stored logs on stackdriver for the following components:
- router
- enricher (Docker enrichers only)
- ensembler (Docker and pyfunc ensemblers only)
- ensembler building logs (pyfunc ensemblers only)
=> feat(ui): Add stackdriver links to logs tab

api/api/openapi.bundle.yaml, api/api/specs/routers.yaml, api/turing/generated/model_big_query_dataset.go, api/turing/generated/model_big_query_dataset_config.go, api/turing/generated/model_big_query_sink.go, api/turing/generated/model_big_query_sink_config.go, api/turing/generated/model_dataset.go, api/turing/generated/model_ensembler_config.go, api/turing/generated/model_ensembler_config_kind.go, api/turing/generated/model_ensembler_infra_config.go, api/turing/generated/model_ensembling_job_ensembler_spec.go, api/turing/generated/model_ensembling_job_ensembler_spec_result.go, api/turing/generated/model_ensembling_job_meta.go, api/turing/generated/model_ensembling_job_prediction_source.go, api/turing/generated/model_ensembling_job_result_type.go, api/turing/generated/model_ensembling_job_sink.go, api/turing/generated/model_ensembling_job_source.go, api/turing/generated/model_ensembling_job_spec.go, api/turing/generated/model_ensembling_resources.go, api/turing/generated/model_env_var.go, api/turing/generated/model_save_mode.go, api/turing/models/autoscaling_policy.go, api/turing/validation/validator_test.go, sdk/turing/generated/model/autoscaling_policy.py
Previously in #380, the autoscaling target was refactored to allow strings with decimal places. However, this wasn't exposed (unintentionally) because the autogenerated Go/Python files from the OpenAPI specs weren't updated. This PR removes the regex check (which had previously only allowed integers as target values) in the OpenAPI specs and updates all the necessary Go/Python files as a result of that change.
=> fix(api): Remove regex check for autoscaling target in autogenerated files

.github/workflows/turing.yaml, ui/package.json, ui/src/components/pod_logs_viewer/PodLogsViewer.js, ui/src/components/pod_logs_viewer/PodLogsViewer.scss, ui/yarn.lock
For some still yet to be understood reason, replacing the forked version of `react-lazylog` from https://github.com/gojekfarm/react-lazylog#master with the latest official version of the same package caused the logs viewer to crash due to some styling issues that get triggered when we manually set the height of the logs viewer (or the component containing it):
In the Turing UI, this height is set by the custom style in `PodLogsViewer.scss` (removed in this PR) while in the Merlin UI, it is set by passing it as a prop to the `LazyLog` component. This PR also standardises the way both UIs are setting this value.
Strangely enough, the Merlin UI isn't experiencing these styling issues even after having its `react-lazylog` replaced with the official reason but a deeper look into this will be …
=> fix(ui): Revert upgrade to react-lazylog

.github/workflows/turing.yaml, ui/package.json, ui/src/components/validation.js, ui/src/router/components/form/components/experiment_config/components/client_config/ClientConfigPanel.js, ui/src/router/components/form/components/experiment_config/validation/schema.js, ui/src/router/components/form/validation/schema.js, ui/yarn.lock
In PR #384, the `yup` package had been updated from `0.29.1` to `1.4.0`. However, this huge upgrade had a lot of [breaking changes](https://github.com/jquense/yup/blob/master/CHANGELOG.md) (see the [latest](https://github.com/jquense/yup) README.md vs the [old](https://github.com/jquense/yup/tree/v0.29.1) one) and effectively broke most of the existing validation schemas in the Turing UI. This PR serves to fix those broken validation schemas - these changes can largely be grouped into the following:
- The `Schema.when` function has been [updated](https://github.com/jquense/yup?tab=readme-ov-file#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema), such that when the builder object (one with the fields `is`, `then`, and sometimes `otherwise` defined) is passed …
=> fix(ui): Fix yup validation bugs

ui/src/router/components/form/validation/schema.js
This PR is a continuation of PR #387 to fix bugs with the yup schemas that are used. It simply changes the schema to the correct type of the `validRouteSchema` (it should be a string and not an object).
=> fix(ui): Fix incorrect yup schema

ui/package.json, ui/src/providers/experiments/ExperimentEngineContextProvider.js, ui/yarn.lock
It seems like after upgrading yup from `0.29.1` to `1.4.0`, we have broken the its compatibility with the `@overgear/yup-ast` [package](https://github.com/WASD-Team/yup-ast). This package is ancient; it's last published 6 years ago and no longer receives any updates because the original contributors have left the company and do not have any permissions/licenses to continue contributing to them. Their [replacement](https://github.com/WASD-Team/yup-ast/issues/10#issuecomment-610873654) is the `@demvsystems/yup-ast` [package](https://github.com/demvsystems/yup-ast), which works _almost_ exactly the same as before.
This package is used when parsing the `yup`-like schema that's served over an API server endpoint (see https://github.com/caraml-dev/xp/blob/cb06edaaf409077b5abf7fed0b803984b6decf7e …
=> fix(ui): Replace deprecated overgear/yup-ast package with demvsystems/yup-ast

ui/src/router/components/form/validation/schema.js
This PR introduces an additional fix to the yup validation schema, as a follow up from #387. In particular, the fix in this PR addresses this change:
- When using the same `Schema.when` function but passing a function directly as an argument instead of the builder object, the signature of the expected function has also been updated from `(value, schema)=> Schema): Schema` to `(values: any[], schema) => Schema): Schema`.
Existing schemas that do not follow this convention now have been updated to reflect the new expected array:
Example:
```javascript
// before
some_field: yup.string().when("some_other_field", (some_other_field, schema) =>
some_other_field ? yup.string().required("this is needed") : schema
),
// after
some_field: yup.string().when("some_other_field", ([some_other_field], …
```
=> fix(ui): Fix min replica yup validation schema

api/turing/api/appcontext.go, api/turing/cluster/controller.go, api/turing/cluster/controller_test.go, api/turing/cluster/labeller/labeller.go, api/turing/cluster/labeller/labeller_test.go, api/turing/config/config.go, api/turing/service/ensembling_job_service_test.go
When creating a namespace object in Kubernetes, add label “{prefix}/managed: true”. This will help when we want to modify resources created by CaraML services in a shared cluster, e.g. configuring log for the managed namespace only
- add `NamespaceLabelPrefix` in configuration, so `InitKubernetesLabeller` can use the configured namespace prefix
- add the label when creating namespace
=> chore: add managed by label to namespace

api/turing/webhook/request.go, api/turing/webhook/webhook.go, api/turing/webhook/webhook_test.go
Changing the structure of the payload send from Turing to a webhook call, so we have the same structure across [Merlin](https://github.com/caraml-dev/merlin/blob/main/api/webhook/request.go) and Turing. From
```
{
"event_type": "on-model-endpoint-created",
"data": {} // the data being either ensembler/router/router_version 
}
```
to
```
{
"event_type": "on-model-endpoint-created",
"data": {
"ensembler": {}, // omit if empty
"router": {}, // omit if empty
"router_version": {} // omit if empty
}
}
```
I make the payload with this structure in case in the future we want to put several object in the payload (instead of just one object like now). I’m open to any advice if you have other opinions
=> chore: change webhook payload structure

api/turing/config/config.go, api/turing/imagebuilder/imagebuilder.go
Similar to what had been performed for Merlin in this PR https://github.com/caraml-dev/merlin/pull/621, this PR introduces a new mechanism for environment variables from the Turing API server to be propagated to **_the build environment of the Kaniko build jobs_** that it spins up, reducing the need for redundant repetition of configuration, especially if these environment variables are common to both the Turing API server and the build environment of the Kaniko build jobs.
Since these variables are passed to the Kaniko build jobs as build arguments (as opposed to environment variables of the container where the image gets built; see https://github.com/GoogleContainerTools/kaniko/issues/2824 for more details), these variables get passed as additional arguments in the Kaniko build job.
- …
=> feat(image-builder): Add mechanism to pass api server env vars to kaniko build jobs

api/turing/cluster/spark.go
Similar to https://github.com/caraml-dev/merlin/pull/623, currently, the Spark driver service account that is created for every batch ensembling job does not have permissions to create ConfigMaps that its Spark executor(s) require(s). This is a problem in clusters with RBAC enabled and this PR simply adds the missing rule on ConfigMap resources for the Spark driver service account.
- `api/turing/cluster/spark.go` - Addition of configmaps as an additional rule
=> fix(api): Add configmaps as a resource to the spark driver role rules

api/turing/cluster/spark.go, api/turing/cluster/spark_test.go, api/turing/config/config.go
Similar to https://github.com/caraml-dev/merlin/pull/624, this simple PR simply adds a tiny feature to allow the API server to pass certain pre-configured environment variable values from its environment to the Spark drivers and executors (for batch prediction) that it spins up.
- `api/turing/cluster/spark.go` - Addition of a step to add pre-configured API server environment variables to the Spark driver/executor manifest
- `api/turing/config/config.go` - Addition of a new config field to specify the environment values mentioned above
=> feat(batch-jobs): Add step to pass API server env vars to spark jobs

api/turing/cluster/labeller/labeller.go, api/turing/cluster/servicebuilder/fluentd.go
In certain environments there is a constraint for logger volume, setting the default value to 20Gi
=> chore: increase log volume size

api/turing/batch/ensembling/controller.go
Adding a check to retrieve the Google service account in ensembling job creation only if the account name is provided
=> chore: retrieve google sa in ensembling job only if it's specified

.github/workflows/pyfunc-ensembler-job.yaml, .github/workflows/pyfunc-ensembler-service.yaml
The MR adds fetch-depth option to checkout@v4 actions, thus pulling the whole repo in the gitlab pipeline
=> add fetch depth option to checkout actions

engines/pyfunc-ensembler-job/Makefile, engines/pyfunc-ensembler-service/Makefile
It appears that the ensembler job/service setup steps now could no longer run because `pipenv` somehow present in the environment where they run in do not have `pipenv` preinstalled. This PR simply adds a step to the setup Makefile recipe to explicitly install `pipenv`.
=> fix(ensembler): Add pipenv installation

engines/pyfunc-ensembler-job/Makefile, engines/pyfunc-ensembler-job/requirements.txt, engines/pyfunc-ensembler-service/Makefile, engines/pyfunc-ensembler-service/tests/conftest.py, engines/pyfunc-ensembler-service/tests/test_ensembler_runner.py
Unlike what was mentioned in #411, there was no need for Turing to be using `pipenv` at all as it was already originally using conda as a package manager. This PR removes all instances where `pipenv` was used and replaces it with what was originally there before #404.
=> fix(ensembler): Remove all pipenv usage
